### ISSUE TITLE
Manual Patching?

### ISSUE THREAD

**Issue by smhmd** [bakkeby/dwm-flexipatch#1]
I have this enhanced `fakefullscreen` [patch](#the-patch) that enables tiling fullscreen only when it's needed made by Aaron Duxler (made `ru_gaps` patch as well). This patch is not published though. I'm not a C developer and struggled with patches a bit, so these repos are a godsend. Is it ever a good idea to apply patches to `dwm-flexipatch` such as this one?

---

Also, since it's gibberish to me, if you could add these functionalities to the patch, I would really appreciate it:
the patch tries to distinguish between tiling fullscreen (two or more visible clients) and normal fullscreen (single visible client including monocle mode):
  - normal fullscreen without always on top (but removes the bar, just always other clients to lay on top of it).
  - tiling fullscreen removes border of `mpv` if "F" is pressed twice.
  - `chromium`, as opposed to `firefox`, does not adapt itself to the limited viewport automatically in tiling fullscreen. I fix this by moving its position on the stack. 
![image](https://user-images.githubusercontent.com/46059092/69254933-40110780-0bb7-11ea-8737-63436a1ba7d8.png)

---

### The patch:
```diff
diff -up a/dwm.c b/dwm.c
--- a/dwm.c	2019-09-26 12:43:27.579531242 +0200
+++ b/dwm.c	2019-09-26 21:54:20.177938682 +0200
@@ -1476,12 +1476,17 @@ setfullscreen(Client *c, int fullscreen)
 		XChangeProperty(dpy, c->win, netatom[NetWMState], XA_ATOM, 32,
 			PropModeReplace, (unsigned char*)&netatom[NetWMFullscreen], 1);
 		c->isfullscreen = 1;
-		c->oldstate = c->isfloating;
-		c->oldbw = c->bw;
-		c->bw = 0;
-		c->isfloating = 1;
-		resizeclient(c, c->mon->mx, c->mon->my, c->mon->mw, c->mon->mh);
-		XRaiseWindow(dpy, c->win);
+		if ( selmon->lt[selmon->sellt]->arrange == &monocle ||  
+				(nexttiled(selmon->clients) != NULL && 
+				nexttiled(nexttiled(selmon->clients)->next) == NULL))
+		{
+			c->oldstate = c->isfloating;
+			c->oldbw = c->bw;
+			c->bw = 0;
+			c->isfloating = 1;
+			resizeclient(c, c->mon->mx, c->mon->my, c->mon->mw, c->mon->mh);
+			XRaiseWindow(dpy, c->win);
+		}
 	} else if (!fullscreen && c->isfullscreen){
 		XChangeProperty(dpy, c->win, netatom[NetWMState], XA_ATOM, 32,
 			PropModeReplace, (unsigned char*)0, 0);
```

**Comment by bakkeby** [comment]
Is this meant to be on top of the fakefullscreen patch or just a patch on it's own?

I tried it on it's own and it seemed to get a bit confused when you try to fullscreen a floating window, put it back into tile again. If you fullscreen and remove fullscreen then I ended up with a floating window again.

I use proper fullscreen very frequently as part of my workflow so the fakefullscreen patch has never had that much appeal for me personally. Being able to fake fullscreen on a per client basis, e.g. only allow fake fulllscreen for the `mpv` application, might make for a more interesting solution.

**Comment by alivefromupstairs** [comment]
- Yes, this is a standalone patch. not on top of `fakefullscreen`
- I see that fullscreen struggles when floating. I never actually tried that. (dragging and resizing seems to be disabled as well.)
-  you are absolutely right. having normal fullscreen on `F11` and tiling fullscreen on `Mod+F11` for example (i.e. tiling fullscreen on demand) is a much better deal. (normal fullscreen should allow other clients to be on top idealy.)

I personally use fakefullscreen with browsers to have as much screen real estate as possible when coding.

**Comment by bakkeby** [comment]
Hi @alivefromupstairs,

I pushed a patch to be able to toggle fake fullscreen on a per client basis, enabled with the `FAKEFULLSCREEN_CLIENT_PATCH` toggle in patches.h. It's compatible with the toggle fullscreen and lose fullscreen patches.

The default keybinding is `MOD+Shift+y`, but of course I'd recommend setting this to something more convenient. Personally I use `MOD+f` and `MOD+Shift+f`.

Perhaps you'd like to give this a go.

Thanks,

-Stein

**Comment by alivefromupstairs** [comment]
Could you, please, post a diff for `fakefullscreen_client_patch` that would apply to bare `dwm`? `dwm-flexipatch` currently is working against me as I have not configured it fully yet. 

Things are not perfect with the patch. Currently, Aaron's take was a nicer UX for its sane defaults/predictability. "you want normal fullscreen? go to Monocle."

But as I said, to try the patch in my utmost comfort would allow me to judge it better. As of right now:
- `togglefakefullscreen`, in my opinion, should enable tiling fullscreen and go fullscreen. if the client is already in fullscreen, it should toggle between tiling and normal. if the client is not in fullscreen and the user pressed `F11`/`f`, the client should go normal fullscreen regardless of the last mode. 

- I can't get `chromium` to go normal fullscreen after I tile it once.

- `fakefullscreen_client_patch` also does not refresh `chromium`. (for reference, Aaron's refreshed). steps to reproduce:
  - open `chromium` in tiling fullscreen and another client in nothing (terminal, for instance).
  - kill the terminal and exit `chromium`'s fullscreen. 
![image](https://user-images.githubusercontent.com/46059092/69354620-b0d02680-0c80-11ea-928c-cf748270b129.png)
(the left half is completely usable, the other half is a frozen image.)

Ultimately, my gripe with the patch comes down to not knowing which mode I'm currently in. It's unpredictable. I rage-clicked a few times already. Maybe some visual clue in the bar (which would be hidden half the time).

Also, did I miss `ru_gaps` in `patches.h`, or is it just not supported? as it integrates well with `fakefullscreen`.
>https://dwm.suckless.org/patches/ru_gaps/
> This patch also incorporates the noborder patch, but without the check for 'is not fullscreen', to make it work properly with fakefullscreen.

Thank you. And I apologize as I myself am not sure how to best do this. The context-based solution seems saner.

**Comment by alivefromupstairs** [comment]
> It's compatible with the toggle fullscreen and lose fullscreen patches.
does the former allow me to

**Comment by alivefromupstairs** [comment]
>It's compatible with the toggle fullscreen and lose fullscreen patches.
Does the former allow me to put clients on top of a fullscreened client? If so, which patch is that exactly?

**Comment by bakkeby** [comment]
> _Ultimately, my gripe with the patch comes down to not knowing which mode I'm currently in. It's unpredictable. I rage-clicked a few times already._

I can understand your frustration, but I am fairly sure that your problem is trying to do this with a complicated application like`chromium` in the first place. For testing purposes I would recommend using something more lightweight like opening a picture using `eog` - that predictably hides the application bar when it goes fullscreen, and shows it again when it leaves fullscreen.

The thing here is that dwm is a window manager, not an _application_ manager. It has no control whatsoever when it comes to what goes on inside the application. What it _can_ do is to send hints to the application, e.g.
> _hey buddy, you might want to consider going fullscreen now_

whether the application takes note of that or not is up to the application itself. Chromium, and Google Chrome for that matter, seemingly do not take note of this and you have to explicitly use the application keyboard shortcut `F11` to go into fullscreen (this has nothing to do with dwm mind you).

Incidentally because of this I have found that you don't actually _need_ fake fullscreen to get a fullscreen Chromium. Using the application shortcut `F11` then toggling off fullscreen within dwm seems to leave you with a fullscreen tiled browser.

-----

If you really want a bare dwm with this patch then you can use the [flexipatch-finalizer](https://github.com/bakkeby/flexipatch-finalizer), it removes all the unused code. That said there is nothing stopping you from using dwm-flexipatch with your already configured config.h, all you need is the keybinding to trigger `togglefakefullscreen`.

-----

About [ru_gaps](https://dwm.suckless.org/patches/ru_gaps/), no I don't have that one. There are many gaps related patches, and this one as many others are only for the `tile` layout. If you need gaps I only have the VANITYGAPS_PATCH in dwm-flexipatch.

-----
>> It's compatible with the toggle fullscreen and lose fullscreen patches.
> 
> Does the former allow me to put clients on top of a fullscreened client? If so, which patch is that exactly?

Yes you can. There are references for most patches in [patches.h](https://github.com/bakkeby/dwm-flexipatch/blob/master/patches.h), e.g. my [diff](https://github.com/bakkeby/dwm-vanitygaps/blob/master/patches/dwm-togglefullscreen-6.2.diff). There's also https://dwm.suckless.org/patches/actualfullscreen/ which is very similar.

-----

All in all if you are using your browser to have access to online IDEs, have you considered trying out [surf](https://surf.suckless.org/)?

If Aaron's solution works better for your workflow then I would recommend you to stick with that.
