### ISSUE TITLE
Any plans to include pango patch?

### ISSUE THREAD

**Issue by somospocos** [bakkeby/dwm-flexipatch#10]
https://dwm.suckless.org/patches/pango/dwm-pango-6.0.diff won't apply to dwm-6.2, because too much code structure has changed.

**Comment by bakkeby** [comment]
From what I understand dwm 6.2 adds both TrueType font support and fallback fonts, so the only additional thing the pango patch would have to offer would be the simple markup for status messages.

I tried to use this patch once, but due to conflicts with the way 6.2 handles fonts it was not straightforward to port this patch and I did not have much luck to be honest.

As such I don't have any immediate plans to include this patch.

**Comment by somospocos** [comment]
>  the only additional thing the pango patch would have to offer would be the simple markup for status messages

It is exactly what I was aiming for. I was planning to use pango markup to mitigate issues like small icons for narrow fonts without resorting to fallback fonts.

**Comment by bakkeby** [comment]
There was an email sent to hackers@suckless.org on the 1st of May with the subject of:
> [hackers] [dwm][PATCH] Using pango markup for status text

including this patch (renamed to .txt because github doesn't support .diff for some reason)
[dwm-pango-20200428-f09418b.diff.txt](https://github.com/bakkeby/dwm-flexipatch/files/4765486/dwm-pango-20200428-f09418b.diff.txt)

**Comment by somospocos** [comment]
Thank you for taking time to let me know. I am not following the suckless mailing list, but I am aware of the patch because it was announced on Reddit as well.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
