### ISSUE TITLE
Patch Request: statusallmons

### ISSUE THREAD

**Issue by BBaoVanC** [bakkeby/dwm-flexipatch#101]
[statusallmons](https://dwm.suckless.org/patches/statusallmons/) draws the statusbar on all monitors instead of just the primary one.

**Comment by BBaoVanC** [comment]
Figured out how to do it to the statusbar (barrules in config.h) but not for systray.

**Comment by bakkeby** [comment]
Yes I was going to say that the `statusallmons` patch exists on the [1.0](https://github.com/bakkeby/dwm-flexipatch/tree/dwm-flexipatch-1.0) branch of dwm-flexipatch which uses the traditional bar. It was made redundant when I integrated [barmodules](https://github.com/bakkeby/patches/wiki/barmodules) which makes it more flexible when it comes to configuration.

You have already figured it out, but for anyone else reading over this enabling `statusallmons` can be achieved by changing the monitor value for the module from `'A'` (which makes the status display on the currently active monitor as per dwm default) to `-1` (show on all monitors).
https://github.com/bakkeby/dwm-flexipatch/blob/72564eb39478c52745b6f8927de516dd2af52b97/config.def.h#L484

When it comes to the systray you can configure it to show on all monitors, but the result will be that the systray flickers back and forth when the bars are updated.

The reason why you can't have the systray show on all monitors is because X does not support window duplication (if there is such a term). This is the same reason why you can't have, say, a terminal window on one monitor and have the exact same terminal window being displayed on another monitor as well. The systray itself is a window and each of the systray icons are separate windows.

**Comment by BBaoVanC** [comment]
Is it possible to create multiple systray windows and then position each one for each monitor?

**Comment by bakkeby** [comment]
That is something one could try, but the individual systray icons would only be on one of the two systray windows and you'd have to have a way to determine in which systray a new icon is to appear (easiest would probably be to go with the systray on the current monitor). Not sure how convenient this would be.
