### ISSUE TITLE
dwm-flexipatch - figuring out what variable is for what color.

### ISSUE THREAD

**Issue by apoorv569** [bakkeby/dwm-flexipatch#109]
I have tried to set different values to different variables to see what they change, so I can add a comment to remember what the variable changes color for. I have added some comments, but the one's that have empty comment are one's I cannot figure out what they are for.

```
static char normfgcolor[]                = "#d3869b";  /* layout and default widget colors */
static char normbgcolor[]                = "#282828";  /* bar color */
static char normbordercolor[]            = "#928374";  /* inactive window border color */
static char normfloatcolor[]             = "#ff0000";  /* */

static char selfgcolor[]                 = "#ff0000";  /* */
static char selbgcolor[]                 = "#00ff00";  /* */
static char selbordercolor[]             = "#ff0000";  /* */
static char selfloatcolor[]              = "#0000ff";  /* */

static char titlenormfgcolor[]           = "#1d2021";  /* unactive title bar font color */
static char titlenormbgcolor[]           = "#a9b665";  /* unactive title bar color */
static char titlenormbordercolor[]       = "#444444";  /* */
static char titlenormfloatcolor[]        = "#db8fd9";  /* */

static char titleselfgcolor[]            = "#1d2021";  /* active title bar font color */
static char titleselbgcolor[]            = "#a9b665";  /* active title bar color */
static char titleselbordercolor[]        = "#005577";  /* */
static char titleselfloatcolor[]         = "#005577";  /* */

static char tagsnormfgcolor[]            = "#bbbbbb";  /* unactive tag font color */
static char tagsnormbgcolor[]            = "#282828";  /* unactive tag color */
static char tagsnormbordercolor[]        = "#444444";  /* */
static char tagsnormfloatcolor[]         = "#db8fd9";  /* */

static char tagsselfgcolor[]             = "#1d2021";  /* active tag font color */
static char tagsselbgcolor[]             = "#a9b665";  /* active tag color */
static char tagsselbordercolor[]         = "#005577";  /* */
static char tagsselfloatcolor[]          = "#005577";  /* */

static char hidfgcolor[]                 = "#005577";  /* */
static char hidbgcolor[]                 = "#222222";  /* */
static char hidbordercolor[]             = "#005577";  /* */
static char hidfloatcolor[]              = "#f76e0c";  /* */

static char urgfgcolor[]                 = "#bbbbbb";  /* */
static char urgbgcolor[]                 = "#222222";  /* */
static char urgbordercolor[]             = "#ff0000";  /* */
static char urgfloatcolor[]              = "#db8fd9";  /* */
```

if you can let me know, what those variables are for it would be a great help.

**Comment by bakkeby** [comment]
This turned out to be a bit longer than anticipated, but I hope it answers most of your questions.

It is better to look at the color setup instead and what scheme they relate to (if that is not obvious from the variable names). You can also search the code for where these are used to get a better understanding of it.

```c
static char *colors[][ColCount] = {
    /*                       fg                bg                border                float */
    [SchemeNorm]         = { normfgcolor,      normbgcolor,      normbordercolor,      normfloatcolor },
    [SchemeSel]          = { selfgcolor,       selbgcolor,       selbordercolor,       selfloatcolor },
    [SchemeTitleNorm]    = { titlenormfgcolor, titlenormbgcolor, titlenormbordercolor, titlenormfloatcolor },
    [SchemeTitleSel]     = { titleselfgcolor,  titleselbgcolor,  titleselbordercolor,  titleselfloatcolor },
    [SchemeTagsNorm]     = { tagsnormfgcolor,  tagsnormbgcolor,  tagsnormbordercolor,  tagsnormfloatcolor },
    [SchemeTagsSel]      = { tagsselfgcolor,   tagsselbgcolor,   tagsselbordercolor,   tagsselfloatcolor },
    [SchemeHid]          = { hidfgcolor,       hidbgcolor,       hidbordercolor,       hidfloatcolor },
    [SchemeUrg]          = { urgfgcolor,       urgbgcolor,       urgbordercolor,       urgfloatcolor },
}
```

Each scheme has four defined colors (or three if you do not use the [float border color](https://dwm.suckless.org/patches/float_border_color/) patch).

The foreground (fg) and background (bg) colors are only used in relation to the bar.

The border color and the float border color are only used in relation to the color of the border drawn around windows.

A bare dwm 6.2 has only two schemes:
   - **SchemeNorm** - This is the normal scheme that are used by default for all clients and it also controls the default colors for the bar (i.e. background color and color of the font used for the tags, layout icon, and the status). By default dwm only has a single window title, but if you use awesomebar, fancybar, bartabgroups, etc. then this is also used for unselected window titles. If the float border color patch is used then floating clients should have a different border color.
   - **SchemeSel** - This is the scheme used for the _selected_ client (note how the currently focused client has a different window border). The selected scheme is also used to highlight the currently selected tags and is by default used for the window title (as there is only one unless you use awesombar, etc.).

The remaining color schemes were added by various patches.

For dwm-flexipatch the complexity handling all these color schemes and the different situations they would be used had grown to be quite ridiculous and just color configuration took up more than 200 lines in config.h, e.g. there was four sections like this depending on whether float border colors and [vtcolors](https://dwm.suckless.org/patches/vtcolors/) were used:
https://github.com/bakkeby/dwm-flexipatch/blob/9c2283dec94d27b4812262b73c308e48201da41f/config.def.h#L261-L277

If you open the file above then you'll see just how unintuitive it was to maintain, let alone to configure.

When I was integrating barmodules into dwm-flexipatch I was anyway straying from the path of having an intact 6.2 build of dwm and respecting each path more or less faithfully, so I decided to simplify and unify the color schemes used by the various patches.

Now to answer your actual question the schemes used for dwm-flexipatch are then as follows:
   - **SchemeNorm** - This defines the background color of the bar and the border color of the bar (if used), it also controls the border color of inactive windows. 
   - **SchemeSel** - For the most part this controls the border color of the selected client, but also has a guest appearance in the [tab](https://dwm.suckless.org/patches/tab/), powerline tags, and [bartabgroups](https://dwm.suckless.org/patches/bartabgroups/) patches.
   - **SchemeTitleNorm** - In general this controls the window title of unselected clients in the (single, and default) wintitle, awesomebar, fancybar, bartabgroups and flexwintitle bar modules.
   - **SchemeTitleSel** - In general this controls the window title of the selected client in the (single, and default) wintitle, awesomebar, fancybar and flexwintitle bar modules. In the bartabgroups module this is used to highlight the active group (master, stack or floating) while SchemeSel is used for the selected client.
   - **SchemeTagsNorm** - This controls the colors of inactive tags. This is also used in relation to the [taggrid](https://dwm.suckless.org/patches/taggrid/) patch. The border and floating colors of this scheme is currently not used. This originates from the [titlecolor](https://dwm.suckless.org/patches/titlecolor/) patch.
   - **SchemeTagsSel** - As above, just that it is used for active tags.
   - **SchemeHid** - This controls the colors of _hidden_ clients on the bar. The original [awesomebar](https://dwm.suckless.org/patches/awesomebar/) patch added functionality to be able to hide and reveal clients by clicking on the window title. With barmodules this was refactored such that awesomebar only handles the arranging of window titles on the bar while the feature of hiding and revealing clients was made available for all window title handlers, enabled through `BAR_WINTITLEACTIONS_PATCH`. Try the default keyboard shortcut of `MOD+Ctrl+z` with window title actions enabled.
   - **SchemeUrg** - Unless you use the [focusonnetactive](https://dwm.suckless.org/patches/focusonnetactive/) patch windows that require attention get the urgency bit set. In a bare 6.2 dwm this means that the foreground and background colors are inverted for the client (and the tag if the client is on an unselected tag) until you focus on it. The the [urgentborder](https://dwm.suckless.org/patches/urgentborder/) patch introduces a new color scheme so that the client requiring attention can be spotted more easily by having a bright red border for example. This also applies to the color scheme used in the bar. You can test this with `wmctrl -a`.

As for the remaining SchemeFlex* color schemes these are all in relation to the flexwintitle bar module which is based on bartabgroups and uses a different color scheme depending on how clients are arranged - intended to be used with flextile. You shouldn't need to worry about this unless you decide to go down that route.
