### ISSUE TITLE
Error Message When Recompiling

### ISSUE THREAD

**Issue by sgreenden** [bakkeby/dwm-flexipatch#116]
I am really sorry to be asking this here, if it isn't your jurisdiction, you can just close this, but when I run the sudo make install command, I get the following error message:

```make
rm -f dwm drw.o dwm.o util.o dwm-6.2.tar.gz

rm -f dwm-msg

dwm build options:

CFLAGS   = -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2   -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -DVERSION="6.2" -DXINERAMA

LDFLAGS  = -L/usr/X11R6/lib -lX11 -lXinerama -lfontconfig -lXft

CC       = cc
cc -c -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2   -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -DVERSION=\"6.2\" -DXINERAMA drw.c

cc -c -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2   -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -DVERSION=\"6.2\" -DXINERAMA dwm.c

In file included from patch/include.c:63,
                 from dwm.c:788:
patch/bar_fancybar.c:65:1: warning: ‘click_fancybar’ defined but not used [-Wunused-function]
   65 | click_fancybar(Bar *bar, Arg *arg, BarArg *a)
      | ^~~~~~~~~~~~~~
patch/bar_fancybar.c:8:1: warning: ‘draw_fancybar’ defined but not used [-Wunused-function]
    8 | draw_fancybar(Bar *bar, BarArg *a)
      | ^~~~~~~~~~~~~
patch/bar_fancybar.c:2:1: warning: ‘width_fancybar’ defined but not used [-Wunused-function]
    2 | width_fancybar(Bar *bar, BarArg *a)
      | ^~~~~~~~~~~~~~
In file included from patch/include.c:60,
                 from dwm.c:788:
patch/bar_wintitle.c:46:1: warning: ‘click_wintitle’ defined but not used [-Wunused-function]
   46 | click_wintitle(Bar *bar, Arg *arg, BarArg *a)
      | ^~~~~~~~~~~~~~
patch/bar_wintitle.c:8:1: warning: ‘draw_wintitle’ defined but not used [-Wunused-function]
    8 | draw_wintitle(Bar *bar, BarArg *a)
      | ^~~~~~~~~~~~~
patch/bar_wintitle.c:2:1: warning: ‘width_wintitle’ defined but not used [-Wunused-function]
    2 | width_wintitle(Bar *bar, BarArg *a)
      | ^~~~~~~~~~~~~~

cc -c -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2   -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -DVERSION=\"6.2\" -DXINERAMA util.c

cc -o dwm drw.o dwm.o util.o -L/usr/X11R6/lib -lX11 -lXinerama -lfontconfig -lXft

/usr/bin/ld: dwm.o: undefined reference to symbol 'XRenderFindVisualFormat'

/usr/bin/ld: /usr/lib/libXrender.so.1: error adding symbols: DSO missing from command line

collect2: error: ld returned 1 exit status

make: *** [Makefile:35: dwm] Error 1
```

I looked up "/usr/bin/ld: /usr/lib/libXrender.so.1: error adding symbols: DSO missing from command line" and I mostly got stuff about developers having issues with specific software & not anything I could see would be related to this issue. I was using DWM before this and did not have this issue compiling, so I am not sure what the cause would be.

**Comment by bakkeby** [comment]
Hi @sgreenden,

there are a handful of patches that depend on additional libraries in order to compile.

For example the [swallow](https://dwm.suckless.org/patches/swallow/) patch depends on three additional libraries:
   - libxcb
   - Xlib-libxcb
   - xcb-res 

Without these dwm will not compile with the swallow patch.

In your case the compilation error is:
```make
/usr/bin/ld: dwm.o: undefined reference to symbol 'XRenderFindVisualFormat'
/usr/bin/ld: /usr/lib/libXrender.so.1: error adding symbols: DSO missing from command line
```
which means that the code wants to use the Xrender library, but the library was not included in the compilation process.

The only patch that relies on this is the alpha patch, so you must have enabled that patch without having uncommented the corresponding line in `config.mk`:
https://github.com/bakkeby/dwm-flexipatch/blob/23c76d13b5376e78c268006da57d132883d5df9b/config.mk#L25-L26

There is a small note about uncommenting this in the `patches.h` file, but this is easy to miss.

Ideally config.mk would use the same directives set in patches.h to determine which libraries are to be included, but while the make supports pre-processor directives the syntax is different. More so the syntax is also different for BSD users.
The other option would be to just always include all libraries, but that would mean that everyone using this would have to install a lot of additional libraries that they may not use.
