### ISSUE TITLE
"Unwanted space" due to show desktop button between taglist and layout icon

### ISSUE THREAD

**Issue by ASWINVENU1** [bakkeby/dwm-flexipatch#128]
I do not remember setting any patches for this feature. I only enabled systray, push, pertag, vanitygaps, and vanitygaps-pertag patches.

![2021-05-08-223842_1366x768_scrot](https://user-images.githubusercontent.com/28093827/117547800-3bf8d400-b04f-11eb-8d39-be761b4020c9.png)

So which part of the code is responsible for this feature? How do disable this?

**Comment by bakkeby** [comment]
If I were to guess then I would say that you have reduced the number of tag icons in your config.h file

https://github.com/bakkeby/dwm-flexipatch/blob/fd958dc631e23a6892e3b6962ae175f2c46c1faa/config.def.h#L362-L366

but you didn't reduce the `NUMTAGS` macro to 6.

https://github.com/bakkeby/dwm-flexipatch/blob/fd958dc631e23a6892e3b6962ae175f2c46c1faa/dwm.c#L74

ref.
https://github.com/bakkeby/dwm-flexipatch/blob/fd958dc631e23a6892e3b6962ae175f2c46c1faa/config.def.h#L336-L338

A bare 6.2 dwm will calculate the length of the tags array for every action you perform, but in dwm-flexipatch you'll have to specifically control that due to the tag icons being more flexible.

**Comment by ASWINVENU1** [comment]
Ah, I see, you're on point. 

Thank you for the insight.
