### ISSUE TITLE
add single-tagset patch

### ISSUE THREAD

**Issue by samyak039** [bakkeby/dwm-flexipatch#150]
please add [single-tagse](https://dwm.suckless.org/patches/single_tagset/) patch in your config.

I know it's a hard one and frankly speaking I was not able to patch it in my config.

If you can do it, then do it. It would be helpful.

**Comment by bakkeby** [comment]
Ha! The single-tagset patch conflicts with pretty much everything else, and it doesn't work properly on 6.2 (as far as I have found in my testing). I once ported it to 6.2 \[[ref](https://github.com/bakkeby/patches/blob/master/dwm/dwm-single_tagset-6.2.diff)\], but to my recollection it wasn't quite stable.

I do understand some people wanting such features, but it would be quite an ordeal to integrate single-tagset into dwm-flexipatch  so I'll have to kindly decline.

That said if you like the idea of the single-tagset patch then I'd recommend that you have a look at my [dusk](https://github.com/bakkeby/dusk) build which has workspaces instead of tags.

**Comment by samyak039** [comment]
No problem :)

your dusk is looking nice, will give it a try.right now I am looking forward to xmonad.
