### ISSUE TITLE
Can ypu add this patch?

### ISSUE THREAD

**Issue by luis-07** [bakkeby/dwm-flexipatch#151]
https://dwm.suckless.org/patches/colorbar/

**Comment by bakkeby** [comment]
In practice you already have that patch with dwm-flexipatch through the different color schemes available.

Is there anything about the colorbar patch that you are missing?

**Comment by bakkeby** [comment]
Yes I only have vanitygaps with dwm-flexipatch. It's a bit of a mess maintaining multiple of these gaps patches side-by-side.

**Comment by luis-07** [comment]
vanitygaps doesn't work i think maybe i am doing anything wrong

**Comment by bakkeby** [comment]
How long ago is it since you cloned dwm-flexipatch? Ref. #147 reported 9 days ago there was an issue where gaps would not be enabled by default (and you'd have to explicitly use the keybinding to enable the gaps, see `togglegaps` keybinding). If you cloned before that then you may want to do a `git pull --rebase` to get the latest updates.

**Comment by luis-07** [comment]
i cloned a new version now it works

**Comment by luis-07** [comment]
how i can activate the patch activetagindicatorbar ?

**Comment by bakkeby** [comment]
> how i can activate the patch activetagindicatorbar ?

Change the `tagindicatortype` config item in config.h
https://github.com/bakkeby/dwm-flexipatch/blob/c968fd9aae7c18e61428bcab0f09798c2f9bdfb5/config.def.h#L82-L83

to one of these values:
https://github.com/bakkeby/dwm-flexipatch/blob/c968fd9aae7c18e61428bcab0f09798c2f9bdfb5/patch/bar_indicators.h#L5-L8

**Comment by bakkeby** [comment]
(copied the above to discussion #153 for future reference)

**Comment by luis-07** [comment]
https://dwm.suckless.org/patches/alternativetags/ is there a patch in this repo to make the bar look exactly the same in the picture?

**Comment by bakkeby** [comment]
No, this user has a lot of custom things going on.

The patch being showcased is just being able to have alternative tags that you can switch to with a keybinding and the screenshots are not representative of the patch.

It is not obvious what the underlines and the different colors mean, but I believe I have managed to figure it out. An underline means that there are clients on that tag. This is then the [activetagindicatorbar](https://dwm.suckless.org/patches/activetagindicatorbar/) patch, just that the line is at the bottom.

By default the underline is green, but it turns blue if the currently selected client is on that tag.

The icons have a dark color by default. The icons are orange if selected, and they turn bright if the currently selected client is on that tag.

The red line over tag 7 means that there is a window requiring attention on that tag.

So in this screenshot the user has:
   - clients on tag 1, 3, 6, 7, 8 and 9
   - the third tag is selected (being orange)
   - the selected client on the third tag is shown on tag 1, 3
   - there is a client requiring attention (having the urgency bit set) on tag 7

You can try out the guys build here if you are interested: https://github.com/pangteypiyush/dwm/

**Comment by explosion-mental** [comment]
Wow that bar is beautiful. Made a patch without the alternative-tag thing since i don't really liked that.
https://github.com/explosion-mental/Dwm/blob/main/Patches/beauty_bar.diff

Idk if this should be added to dwm-flexipatch, maybe separate defines in a way that enables layout color, statusbar color, etc.

**Comment by bakkeby** [comment]
@explosion-mental, beauty_bar lol, fun name.

Separate colors for tags, window titles etc. are already there and being able to specify the scheme for each module is something I can add if need be. Haven't had any requests about that, I suppose it's overwhelming as it is.

The main complexity integrating this one is introducing even more color schemes as well as the convoluted logic of selecting the scheme. If I were to add something like this then I would most likely create a different module for drawing the tags, I'm just not sure if it's worth the effort.

As for
> Until I learn how to properly diff something, you need to manually patch these. 

I was going to outline what I do here, but decided to move it to a separate discussion instead (#160).

**Comment by explosion-mental** [comment]
@bakkeby wow, thank you very much!

Yes, I'm having a bit of a confusing experience with the colors. Do you know what the 'border' column refers on the colors array? ('fg - bg - border' From what I know is the border of the window, but does that matter if we are going to add a Scheme for a bar  "module", say for the title module.)

**Comment by bakkeby** [comment]
@explosion-mental I think you have understood it well enough.

There is this enum in drw.h that refer to these colors:
```c
enum { ColFg, ColBg, ColBorder }; /* Clr scheme index */
```

and this is only ever used in these places:
```c
./dwm.c:799:		XSetWindowBorder(dpy, c->win, scheme[SchemeSel][ColBorder].pixel);
./dwm.c:1055:	XSetWindowBorder(dpy, w, scheme[SchemeNorm][ColBorder].pixel);
./dwm.c:1758:	XSetWindowBorder(dpy, c->win, scheme[SchemeNorm][ColBorder].pixel);
```
(that's `focus`, `unfocus` and `manage` functions)

Unless you make changes of your own the border will only be used for SchemeSel and SchemeNorm.

As we add more color schemes the border color is going to be redundant, left unused.

When defining the colors in your configuration file you can just omit the border though, like this:

```c
static char *colors[][3] = {
       /*                 fg             bg             border	 */
       [SchemeNorm]   = { normfgcolor,   normbgcolor,   normbordercolor },
       [SchemeSel]    = { selfgcolor,    selbgcolor,    selbordercolor  },
       [SchemeTitle]  = { titlefgcolor,  titlebgcolor  },
       [SchemeLayout] = { layoutfgcolor, layoutbgcolor },
};
```

The omitted border colors should be initialised as NULL, but memory will be reserved for the colors in any case and they should just come through as black (`#000000`).

It is of course technically possible to rip this apart so that border colors are defined separately, but it is likely not worth the effort.
