### ISSUE TITLE
Update issue.

### ISSUE THREAD

**Issue by kkYrusobad** [bakkeby/dwm-flexipatch#155]
I cloned master couple of weeks ago and now I am behind the latest update, how can i update my existing build to the latest branch update.
note: I would like to keep my build as is if possible, after update.

**Comment by bakkeby** [comment]
But to answer your question you can just do a:
```bash
$ git pull --rebase
```
The `--rebase` flag is just in case you have committed any changes of your own, in which case you'll want those changes to be applied on top of whatever is being updated. Otherwise you would be trying to apply any updates on top of your own changes which would cause more conflicts down the line.
