### ISSUE TITLE
'xdo show' crashes dwm

### ISSUE THREAD

**Issue by der-zonk** [bakkeby/dwm-flexipatch#156]
I use a little toggle script with xdo to start, if not running and show/hide toggle some apps.. This works for keepass at least.. Yesterday I tried firefox.. hide works, if I show again, dwm crashes.. with mullvad it does not crash but it opens only a not-closeable window in the same size as mullvad has, without any content in it.. I suspect this is normal for dwm... Any chance on getting a fix for this? Haven't tried more apps yet as I don't want dwm to crash hundret times.. already had a keepass database borked because of this hard quit

**Comment by bakkeby** [comment]
Can't replicate in a bare dwm nor in dwm-flexipatch.

Presuming that you are using flexipatch, can you tell me which patches you have enabled?

**Comment by der-zonk** [comment]
oh ok.. Haven't tested with bare dwm..
https://github.com/der-zonk/dwm/blob/master/patches

**Comment by bakkeby** [comment]
Yes I don't know, I wasn't able to replicate using those patches nor by cloning your build.

I'd recommend trying this out using Xephyr and see if you have to do something specific to replicate the issue. As you see the output of dwm directly in the terminal where you run dwm from you can also add print statements to further debug how far it gets or where it fails.

**Comment by der-zonk** [comment]
Well fuck me I guess because in Xephyr it works..

**Comment by bakkeby** [comment]
When running `xdo hide` xdo will unmap the window, resulting in an unmanage call in dwm.

When running `xdo show` xdo will map the window, resulting in a manage call in dwm.

I don't see any specific that would cause an issue in either function. Most likely the issue lies elsewhere, we would just need to know how to replicate the issue consistently.

**Comment by der-zonk** [comment]
Since it works with Xephyr and even you can't replicate it with my own build, I don't even know where to look.
I tried with disabling picom and polybar, still the same.. I don't know what else I could turn off or whatever to narrow it down..
What would be things that differentiate Xephyr from my regular xsession.. I have n.o. idea
How did you use xdo?

**Comment by bakkeby** [comment]
I also tried it in a regular session and couldn't replicate it that either.

I did `xwininfo` and clicked on firefox to get the window id, then ran
```bash
$ xdo hide 0x1a00002
```

```bash
$ xdo show 0x1a00002
```

Can you replicate it consistently at your end, or is it intermittent?

**Comment by der-zonk** [comment]
I recall not having this problem in other wms. I'm also to lazy to try out others right now..
It seems like some programs need the exact pid or wid, while others do not.

Sadly I can't figure out how to write a script to, when I open a program, to wait for it to be managed by the wm, then write the pid to a file and use that file for xdo stuff..
I tried a loop with
`while ! [ "$(wmctrl -l | grep -i "$1")" ]; do sleep 0.1; done && echo "$(wmctrl -l | grep -i "$1" | cut -d' ' -f1)" > /tmp/toggle_"$1"`
But it doesn't give me anything.. I'm pretty dumb when it comes to scripting xD

**Comment by bakkeby** [comment]
Ah, this reminds me of a similar issue I had the other day that was driving me nuts trying to debug and to find the root cause.

Someone once showed me a command using xdo to focus on a window (using the [focusonnetactive](https://dwm.suckless.org/patches/focusonnetactive/) functionality) and to spawn the program if it is not already running.

In the end the command I was looking for was `xdo activate -N firefox || firefox`, but I was fumbling a bit trying out different things before arriving at that conclusion.

So I ran the command of 
```sh
$ xdo show -n firefox
```
and my window manager crashed. Interestingly I could reproduce the issue consistently with the above command.

The error I got from the logs was:
```
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  2 (X_ChangeWindowAttributes)
  Serial number of failed request:  2444
  Current serial number in output stream:  2452
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 177, resource id: 2097193, major code: 20 (GetProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 178, resource id: 2097193, major code: 20 (GetProperty), minor code: 0
```

which did not tell me a whole lot.

I tried this in a bare dwm 6.2 and it crashed there as well. Next I tried this out in openbox and it worked just fine. Then I tried it out in qtile where it worked as well, but I also observed errors being logged there and there was tiled space being reserved for a third window and if I moved my mouse over that area the bar showed the title of Firefox.

I was able to run `xwininfo` on the program which showed:

```
xwininfo: Please select the window about which you
          would like information by clicking the
          mouse in that window.

xwininfo: Window id: 0x1000001 "Firefox"

  Absolute upper-left X:  0
  Absolute upper-left Y:  0
  Relative upper-left X:  0
  Relative upper-left Y:  0
  Width: 636
  Height: 364
  Depth: 0
  Visual: 0x3c8
  Visual Class: TrueColor
  Border width: 0
  Class: InputOnly
  Colormap: 0x0 (not installed)
  Bit Gravity State: ForgetGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +0+0  -644+0  -644-396  +0-396
  -geometry 636x364+0+0
```

I suspect the color depth of 0 might be the reason for the window manager crashing.

In the end my conclusion was that firefox has this invisible window that it uses for some specific purpose and by running the command I inadvertently tried to show it like it was something that could be presented to the user.

Perhaps it is possible to ignore trying to manage such windows in dwm by checking the color depth of the window, but I haven't followed up on that yet. In the end the root cause was me doing something dodgy with tools I did not fully understand.

**Comment by der-zonk** [comment]
It's not only firefox. Mullvad for example has colordepth 24 if that tells u anything and there it's basically the same.
I was thinking because firefox has several processes running with the same class_name, u can't use that. You have to use the specific wid or pid of the actual window.

**Comment by bakkeby** [comment]
In Firefox's case using the class name is fine, in the command where it went wrong I used the lower case `-n` flag which is for the instance name.

If you have any means of getting hold of the `xprop` and `xwininfo` for the misbehaving Mullvad window then that might be useful in terms of finding a fix or a workaround such that dwm doesn't just crash.

Of course one _can_ just blindly ignore BadMatch or BadWindow errors coming from X but I'm not entirely sure how healthy that is.

**Comment by der-zonk** [comment]
Oh I said that wrong my bad.. It's not "the same" in Mullvad, it opens and empty window..

I just tried again.. I think I'm doing something different now than before, now mullvad accepts the name..
I think the problem was I wanted to write a wrapper script to toggle all programs but mullvad misbehaved..
That wrapper script is sadly growing to much with every new pgrogram added because each one needs something different to work xD

I just wanted to have the executable as $1 and check for it in pgrep but this does not work for all.. for keepass it works wonderfully..
you can start it with "keepassxc" and hide/show with xdo hide/show -n "keepassxc".. for some pgrograms I need to add a name or in case of firefox the exact WID, which is a pain in the ass to be honest.. So I quit working on it..

**Comment by bakkeby** [comment]
[jumpapp](https://github.com/mkropat/jumpapp) is a tool like you describe and it seems to work fine, it just has some quirks around client messages which one needs to add support for manually.

I think it is a nice idea. At the same time it is similar to having scratchpads.

**Comment by der-zonk** [comment]
I like to get the most out of the stuff I already have and use on my laptop instead of installing more crap. :D
Jumpapp also uses wmctrl for most stuff. If they can do it I can do it too if I wasn't too lazy to learn proper scripting.
I quit working on it for now but I did not abandon it. xD Reworking my dwm config has higher priority right now.
