### ISSUE TITLE
Patch request : window titlebar

### ISSUE THREAD

**Issue by siduck76** [bakkeby/dwm-flexipatch#178]
Hi @bakkeby , would it be possible to add window titlebar? 

I read it somewhere that [this](https://github.com/dylanaraps/sowm/pull/57/files)  might be helpful

**Comment by bakkeby** [comment]
Personally I wouldn't want to touch that with a stick.

Rather than having a loosely coupled window that one would need to make sure is positioned relative to the window at all times it might be better to go for full reparenting instead, with buttons to close, maximize and minimize windows with a style resembling Windows 97.

I thought one of the appeals of dwm is that it does not do this though. One might as well use awesomewm in that case.

In any case I think this would be rather complicated to integrate even if someone had implemented this as a patch for dwm.

**Comment by siduck76** [comment]
dang! I didnt know it was this complicated. Window titlebar would look useless when in non floating modes so showing the titlebar in floating mode only could be cool . My friend had made a patch for adding a tabbar like thingy with buttons in monoclde mode. 

![image](https://user-images.githubusercontent.com/59060246/129068775-5925b6cc-c495-4b80-998d-4d5233b92824.png)

**Comment by bakkeby** [comment]
I'll presume that's based on the [tab](https://dwm.suckless.org/patches/tab/) patch. The extra buttons in the top right corner looks like they might be useful.

Your colour schemes look prety slick. When I have cleared some of my backlog I'll take a closer look at your build and the many features you have added.
