### ISSUE TITLE
DRAGMFACT + DRAGCFACT (patch idea)

### ISSUE THREAD

**Issue by kronikpillow** [bakkeby/dwm-flexipatch#19]
I haven't tried this and dunno if it works or not, cuz lately I'm exhausted from all the patch testing in here, need a break, but had an idea that if it's not already possible, that it could be a good idea, to have a patch that works with DRAGMFACT + DRAGCFACT, eg so that you can drag CFACTS with your mouse as well :)

btw: Glad I'm keeping you busy :D

**Comment by bakkeby** [comment]
Actually I was thinking about this back when integrating the DRAGMFACT patch, but didn't pursue it as it wasn't particularly important.

I think it might work if one were to use a different modifier, e.g. MOD+Shift, then right click and drag. As such it might be a good idea to implement the DRAGMFACT properly as well, rather than piggy-backing on the resizemouse functionality.

By default, if you hold MOD then right-click and start dragging then you can resize the currently selected tiled window (and thus make it floating). If you enable the DRAGMFACT patch then this resizing only works if the window is already floating, otherwise the mfact is dragged.

Also the patch is coded to only look for mouse movement along the x-axis. It would be prudent to also make it consider the y-axis so that it would be more intuitive with other layouts such as the bottom stack, as an example.

Could be an interesting small project.

**Comment by bakkeby** [comment]
I added my initial take on the dragcfact patch, think it works rather smoothly.

I'll still want to revamp the dragmfact at some point.

**Comment by bakkeby** [comment]
Implemented my ideas for dragmfact, this just feels so much better.

**Comment by bakkeby** [comment]
NB: Default shortcuts are now:
   - mod+shift+rightclick and drag to change cfact
   - mod+shift+leftclick and drag to change mfact

**Comment by kronikpillow** [comment]
It's nice, although I'm not sure how much I like the need to press mod+shift to have this functionality, but I guess it serves its needs

**Comment by bakkeby** [comment]
As with most things it is just configuration. If you really wanted to you can just set the modifier to 0 and you can just click and drag to change mfact. I have tried this and can confirm that it works, just that you won't actually be able to click on windows - which might, just might, be an issue :)

**Comment by kronikpillow** [comment]
Ok bro :) tyvm :)
