### ISSUE TITLE
multi-monitor setup

### ISSUE THREAD

**Issue by yanboyang713** [bakkeby/dwm-flexipatch#213]
I have two monitors. However, currently have the same tags for every monitor. Is there any patch that can separate different tags for every monitor?

**Currently**:
Monitor one: tags 1, 2, 3, 4 ...
Monitor two: tags 1, 2, 3, 4 ...

Want to become:
Monitor one: tags 1, 2, 3, 4, 5
Monitor two: tags 6, 7, 8, 9, 10

Thanks for your help.

This is my current DWM configuration.
https://github.com/yanboyang713/dwm-flexipatch.git

My Blog about DWM (Have NOT DONE)
https://www.yanboyang.com/dwm/

**Comment by bakkeby** [comment]
To answer your exact question yes there is a patch [tagicons](https://github.com/bakkeby/patches/wiki/tagicons) that allows you to have different sets of tags on a per monitor basis. It is an evolution of the older monitortags patch.

As for dwm-flexipatch the `tagicons` patch is already integrated (hardcoded) so it can't be enabled via patches.h.

Refer to the first example in the comment for the `tagicons` setting in your config.h file:

https://github.com/bakkeby/dwm-flexipatch/blob/0404e12dbaca203325f391f751f1188f91a7ef1a/config.def.h#L369-L389

**Comment by yanboyang713** [comment]
Hello @bakkeby,

Thanks for your help.

Let's me have a try. Thanks.

Boyang

**Comment by yanboyang713** [comment]
Hello @bakkeby,

Thanks for your help. Great, this separates different tags for every monitor. Thanks.
But, how can I switch from A to I?

I can type MODKEY + 1, switch to window 1.
But, type MODKEY + A, does NOT work, could NOT switch to windows A.

Boyang

**Comment by bakkeby** [comment]
Hi @yanboyang713,

so the keybindings here are defined as:

https://github.com/bakkeby/dwm-flexipatch/blob/0404e12dbaca203325f391f751f1188f91a7ef1a/config.def.h#L1203-L1211

which uses the following macro:

https://github.com/bakkeby/dwm-flexipatch/blob/0404e12dbaca203325f391f751f1188f91a7ef1a/config.def.h#L772-L776

You can think of the macro as text being copy-pasted for every `TAGKEYS` reference above. 

So MOD+1 will trigger the `view` function to change the tags on the currently selected monitor.

The tag icons are just that, icons. They do not influence the above keybindings in any way. If you change tag 2 to say "EMAIL" then naturally you do not need to do MOD+E+M+A+I+L, just MOD+2 will do.

To focus on another monitor it is expected that you change focus to the other monitor first.

https://github.com/bakkeby/dwm-flexipatch/blob/0404e12dbaca203325f391f751f1188f91a7ef1a/config.def.h#L1055-L1056

Now directly referring to tags on another monitor is something that some people ask about, here is one example:
   - https://www.reddit.com/r/suckless/comments/qsct9h/tagkeys_monitor_2_dwmmonitortags62diff/

It is not particularly complicated to achieve, but it would consume a lot of keys especially with nine tags on each monitor.

If you want something like this then I'd rather recommend looking at something that uses workspaces instead of tags.

\
Thanks,

-Stein

**Comment by yanboyang713** [comment]
Hello Stein @bakkeby ,

Thanks so much for your help. 

Thank you very much for your explanations, and suggestions.

I understand now. Very thanks
