### ISSUE TITLE
Flexipatch patches aren't working

### ISSUE THREAD

**Issue by jbjoeB** [bakkeby/dwm-flexipatch#228]
I installed manjaro on a vm, don't have any other build of dwm running at all

I installed flexipatch did a sudo make clean install and switched to dwm. (That is working fine)

When i go to patches.def.h i choose lets say 3 layouts put them as a 1 run sudo make clean install, everything compiles fine. i log out of dwm and log back in and none of my keybindings are working at all. ive used the alt+ every key combination. I've used alt+shift and every key combination and nothing is working. am i doing something wrong?

Thanks

**Comment by bakkeby** [comment]
Like config.def.h is the default configuration file and config.h is your personal config file, the patches.def.h is the default patches file and patches.h is your personal one. 

Try changing the latter.

**Comment by rharmonson** [comment]
After your initial make, delete config.h then `make clean install`.

**Comment by rharmonson** [comment]
Thank you @bakkeby and @ggumbo79 . I am new to flexipatch and didn't understand the def.h and .h file relationship, either.

**Comment by ggumbo79** [comment]
> Like config.def.h is the default configuration file and config.h is your personal config file, the patches.def.h is the default patches file and patches.h is your personal one.
> 
> Try changing the latter.

Looking around and saw fresh installs of dwm and they just ran flexipatxh and it seemed liked it worked. whenever i change a 0 to a 1 and recomplie nothing. am i suppose to change the keybindings manually? i was advised that config.h is there everytime you compile so just delete it so it gets re-made. sorry i'm  so new to this just need some guidance. dwm seems really nice

**Comment by bakkeby** [comment]
If you clone a bare 6.3 dwm then the first thing you do is to run make once which will copy the default config.def.h to a config.h that you can edit as you please.

In dwm-flexipatch it is the same just that in addition to that the default patches.def.h is copied to a patches.h file that you can edit as you please.

The intention is that you use config.h and patches.h to make all your customisations as these are not in version control (i.e. not tracked by git). 

A lot of people will give the recommendation to delete config.h and recompile and the main reason for this is that patches naturally only change files that are in version control and they get confused by compilation errors that can occur due to new settings missing from config.h.

As an end user it is perfectly fine for you to delete config.h and patches.h before you compile and edit config.def.h and patches.def.h  instead. Having edited these you may later find that you are not able to update via git pull because you have uncommitted changes, in which case you may want to commit the changes before updating. This in turn can lead to conflicts between changes that you have made vs upstream changes. 

If I were to do the same then it would be a lot harder to differentiate between fault configuration and my personal configuration, and it would be very easy to accidentally make the bar fluorescent pink by default for new users :) 

As for the keybindings yes I would recommend that you customise this in a way that works for you, but I would also recommend to work out what patches and workflow works for you before you start worrying about keybindings.
