### ISSUE TITLE
HIDE_VACANT_TAGS leaves empty rectangles

### ISSUE THREAD

**Issue by andbenn** [bakkeby/dwm-flexipatch#230]
With BAR_HIDEVACANTTAGS_PATCH enabled, and looking at the patch description at https://dwm.suckless.org/patches/hide_vacant_tags/ , the third paragraph mentions that the empty rectangles won't be drawn.  I'm not even sure why the filled rectangle would be needed, but separate issue.

Reviewing the older Suckless patches, I can't easily tell if they ever did not draw the empty rectangles.  Checking dwm.c around line 1810, Maybe the patch description is out of date.  I'd appreciate a quick review near future - this issue is purely cosmetic.  Is the Suckless description out of date?

**Comment by bakkeby** [comment]
By empty rectangles do you mean the indicator saying whether the tag has clients or not?

**Comment by bakkeby** [comment]
The patch description on the suckless page should be accurate for the patch on that page.

Many patches do more than one thing. In the case of the hide vacant tags patch it hides empty tags and it removes the tag indicators. 

To make dwm-flexipatch easier to maintain and for compatibility reasons some patches are broken up into different functionalities. In effect the hide vacant tags patch toggle only hides vacant tags as you have observed.

A use case for this is that there are patches that change the tag indicator for example to have an underline instead of a rectangle. If someone wanted hide vacant tags + the underline patch to display then this would add complexity.

Another example is the awesomebar patch which adds window titles for all windows and it adds functionality to hide windows. In dwm-flexipatch the awesomebar patch only provides the window titles, whereas the click functionality and hidden windows is available for all window title patches (fancybar, bartabgroups, etc.).

In dwm-flexipatch if you want to hide the tag indicators then you can change this setting to `INDICATOR_NONE`:
https://github.com/bakkeby/dwm-flexipatch/blob/96820b2d51b7e1bca5ccdd9ce289e9fd278aa767/config.def.h#L107

**Comment by andbenn** [comment]
Thank you thank you thank you for the tagindicatortype tip - it's applied, built and looks great!

Totally understand the near merge hell with this project.  Suffice to say, it's totally awesome and makes experiments easy.

I also have the AwesomeBar patch in my build, and noticed the original diff has some finger crossing keybindings that aren't in dwm-flexipatch.  Such that, MOD-Control-Z can iconify the current window; yet to un-inconify it requires the mouse. 

Resolving, and thank you for your time!

**Comment by bakkeby** [comment]
> MOD-Control-Z can iconify the current window; yet to un-inconify it requires the mouse.

It is undocumented but if you set up a new keybinding to pass `+/-2` instead of `+/-1` to the focusstack function then that will allow you to focus on hidden windows as well.
https://github.com/bakkeby/dwm-flexipatch/blob/96820b2d51b7e1bca5ccdd9ce289e9fd278aa767/config.def.h#L863-L864

It would probably be better to just have a separate function that only focuses on hidden clients instead of both normal + hidden though.
