### ISSUE TITLE
dwmblocks included?

### ISSUE THREAD

**Issue by rharmonson** [bakkeby/dwm-flexipatch#232]
In reviewing [closed](https://github.com/bakkeby/dwm-flexipatch/issues/85) and open issues, I suspect that dwmblocks is not included with dwm-flexipatch and must be cloned, make, and installed separately. I am using dwm-flexipatch 6.3 and the intent is to use statuscmd (signals) for click support.

Is my inference correct?

If true, what would be the recommended and supported dwmblocks source?

**Comment by bakkeby** [comment]
Your inference is correct. I was going to write a more elaborate reply, but as it is a topic that comes up more often than I'd like I decided to dump it all in a discussion entry instead: #233

**Comment by rharmonson** [comment]
The discussion article is well written and should reduce inquiries. I would recommend that you briefly discuss SIGRTMIN and SIGUSR1 beyond citing SIGUSR1 is the old method. Perhaps give a recommendation or pros/cons? Not necessary but it's an open question for me after reading the article--not a complaint.

I am going to give SIGRTMIN a go for I am going to assume the author had a reason for changing the signaling method.

I want to acknowledge your excellent support. You responses are timely and thorough. Thank you!

Closing this issue.

**Comment by bakkeby** [comment]
I don't know the incentive for changing the method or if there are any pros and cons using one over the other.

If I were to guess I'd say most likely the patch authors figured that it was better to hook into the `SIGRTMIN` signals that dwmblocks already implemented rather than using `SIGUSR1`.

Given [this](https://github.com/torrinfail/dwmblocks/commit/5dcb2a0d8413b6e12dfcd188567f95d3832bb2bb) commit I suppose that it may be favourable to use the `SIGUSR1` method if one is on OpenBSD. Both methods should in principle work fine.

**Comment by rharmonson** [comment]
Understood and thank you.
