### ISSUE TITLE
Static borders with flexwintitle patch

### ISSUE THREAD

**Issue by Vinschers** [bakkeby/dwm-flexipatch#240]
After adding the flexwintitle patch, I noticed the border draw stopped working when I disable the tag bar (togglebar function). I believe this happens because the drawfunc from the bar rule is not called when the bar is toggled off. As this patches includes the display of borders inside its draw function, the borders stop behaving correctly.

I wonder if it would be possible to move this part of the code to somewhere where the status of the bar does not matter.

**Comment by bakkeby** [comment]
I see, you are referring to the drawing of the client window borders not the border around the bar.

> I believe this happens because the drawfunc from the bar rule is not called when the bar is toggled off.

Yes that is because of this upstream change that avoids drawing the bar when it is hidden:
https://git.suckless.org/dwm/commit/8657affa2a61e85ca8df76b62e43cb02897d1d80.html

I suppose that I could just omit that if the flexwintitle is used.

Another alternative could be to fall back to dwm defaults and use `SchemeNorm` and `SchemeSel` when the bar is disabled.

> I wonder if it would be possible to move this part of the code to somewhere where the status of the bar does not matter.

This is perfectly possible and I did this in my other [build](https://github.com/bakkeby/dusk), but that would be a rather invasive change and it is not really feasible to integrate into dwm-flexipatch.

**Comment by Vinschers** [comment]
Thank you so much for your response!
I was afraid it'd take a great change to fix this behavior, but I'm glad that you did so in your other build. I'll try to implement this on my build, using yours as a model.
