### ISSUE TITLE
anyway to get home directory path for cool_autostart patch?

### ISSUE THREAD

**Issue by junnunkarim** [bakkeby/dwm-flexipatch#249]
First of all I would like to thank you. Because of your build of dwm and dmenu, I was able to get into making my very own setup. I really appreciate your efforts for making these dwm and dmenu builds. Again I am profoundly grateful to you.

Now I would like to address an issue I was having with the COOL_AUTOSTART patch. I have a script in my ```$HOME/.bin``` directory. If I want to make this script autostart, I have to give the full path of that script. But I wanted to make my build portable, so I would like to get the home directory of the user first and then concatenate ```.bin``` to it and use it inside ```autostart[]``` array. But when I try to use ```getenv("HOME")``` to get the home directory, the compiler reports ```error: initializer element is not constant```. Is there any clean way to achive what I am trying to do?

**Comment by bakkeby** [comment]
For something portable it seems a bit counter intuitive to include something that starts programs automatically. My first thought is that perhaps you might be better of looking at the more traditional autostart patch rather than the cool autostart patch.

The former executes designated shell scripts at startup and you put whatever you want in them, with the caveat that you may have to guard against starting said program again if it is already running.

The latter patch works around that by keeping track of the PID of the process(es) started and forcibly kills said PIDs when dwm exits. In principle it is possible that this logic results in the wrong process being killed if the process ends and another process happens to be assigned the same process ID. Fairly slim chance of this happening in practice though.

To answer your actual question regarding the cool autostart patch I suppose that with some tinkering it might be possible to some hacks in the `autostart_exec` function of that patch to incorporate the HOME path (provided the command does not start with a forward slash of course).

> I have a script in my `$HOME/.bin` directory. If I want to make this script autostart, I have to give the full path of that script.

Do you really have to though? 

The current working directory of dwm should normally be that of your home directory (unless that depends on the login/display manager). You can check the current working directory of dwm with this command, which in my case is my home directory.

```sh
$ ls -l /proc/$(pidof dwm)/ | grep cwd
lrwxrwxrwx 0 sbakkeby 14 May 20:36 cwd -> /home/sbakkeby
```

So I would assume that you could just add a relative path to your executable, e.g.

```c
static const char *const autostart[] = {
	".bin/set_my_background_wallpaper_pretty_please.sh", NULL,
	NULL /* terminate */
};
```

More so if that `.bin` directory is in your `PATH` environment variable and this is set prior to dwm starting then you should be able to just call the executable directly omitting the directory from the path.

**Comment by junnunkarim** [comment]
By portable I meant being able to create my same setup on other computers. Since other computers might have different username, I did not want to hardcode the paths. Sorry about the confusion, I should have mentioned it.

I made a script to reload my setups colorschemes by restarting dwm(using RESTARTSIG_PATCH). I did try out the AUTOSTART_PATCH but it did not reload the programs after restarting dwm. I might have been able to fix this issue but I did not because I liked the method of having all my autostart programs in the config file.

LIke you said, I would have to do some manual checking to avoid unwanted behavior with AUTOSTART_PATCH. So I think using COOL_AUTOSTART_PATCH would be the wise decision for me.

Well, I did not know that the current working directory of dwm was my home directory. I checked and tried using a relative path to my script and it worked perfectly.

Thank you very much for your in depth explanation and solution. :)

**Comment by bakkeby** [comment]
> I made a script to reload my setups colorschemes by restarting dwm(using RESTARTSIG_PATCH)

I'd think using the xrdb patch would be more interesting in this context as with that you can reload colours without having to restart dwm.

**Comment by junnunkarim** [comment]
> I'd think using the xrdb patch would be more interesting in this context as with that you can reload colours without having to restart dwm.

I did recently switch to using ```xrdb patch```. Before I used to compile dwm with a script every time I wanted to switch themes. But after switching to xrdb, it reloads really fast and I don't need to enter my password everytime.

Here are my dotfiles if you want to check them out (not fully complete yet) -
[dotfiles-linux](https://github.com/junnunkarim/dotfiles-linux)
