### ISSUE TITLE
Would you kindly annotate the dwm source code?

### ISSUE THREAD

**Issue by junnunkarim** [bakkeby/dwm-flexipatch#250]
As the title says, would you please make an annotated version of dwm for beginners?
You have very good knowledge about how suckless software workse. So if you annotate the source code, it would help out a lot of people.
Please do consider about it.

**Comment by bakkeby** [comment]
By annotations I presume you mean comments (annotations in programming languages generally means something very specific).

I was actually considering a dwm-commented project a while back but to be honest there wasn't that much interest and it seemed like a lot of effort for very little gain (and ultimately I had more important things to do).

Doing something like that has some problems though; like how much into detail do you go and who is the target audience? Being faced by a wall of text doesn't necessarily make it easier to understand what is going on or how all the parts work together. If you are a beginner and possibly not that familiar with C then it could be even more overwhelming.

The principal aim of the code is to be so simple that it is self-explanatory - and this can be argued to be the case for most of the functions in dwm if you know a bit of C. That said while you can work out what a piece of code does by reading it what it doesn't tell you is the intent and why it was implemented like this instead of 42 other ways it could have been implemented.

One realisation I had was that it would be very challenging to do such a documentation project in an objective manner - it would be far to easy to go on a rant about annoyances that were written the way they are just to save a single line of code.

**Comment by junnunkarim** [comment]
Yes I meant comments. 

Well, isn't beginners who know some C the correct audience to choose because advanced C programmer wouldn't have to give much effort to understand the code.

Is dwm code really self-explanatory? I do know C enough to create some simple cli tools. But I was having a hard time understanding the code. I did understand what some functions do but I did not understand how this connects to the others and why they did implement it this way. Also the variable names are quite confusing.

Now I think having a commented version of the code is better than having no none. So if you think it would be beneficial and if you have some time, please do consider creating one for the beginners who know a bit of C.

**Comment by bakkeby** [comment]
Hi @junnunkarim not that I have _that_ much to say about dwm or its implementation, but I have an early draft adding some comments in https://github.com/bakkeby/dwm-commented should you still be interested.

**Comment by junnunkarim** [comment]
Hello @bakkeby! 
I can't thank you enough for this. I was having a hard time understanding the dwm codebase before. But now I tried reading the some parts of your commented version and I must say I'm understanding significantly better now. I look forward to reading it from the beginning starting tomorrow. I wholeheartedly appreciate your efforts to fulfill this request of mine and I'll try my best to share it to the world. Thank You.
