### ISSUE TITLE
Bartabgroup doesn't follow window border

### ISSUE THREAD

**Issue by par4m** [bakkeby/dwm-flexipatch#256]
Manually patched: 
![image](https://user-images.githubusercontent.com/68808783/171592782-e4d785b1-b041-4ae4-aced-da7558f9ea2f.png)

Flexipatch:
![image](https://user-images.githubusercontent.com/68808783/171593709-9c2b74bd-2a27-413f-9f32-f65e98aac7e7.png)

Not sure what's causing this

**Comment by par4m** [comment]
When the window is resized, the tab bar should also move (which it is) but it should be aligned with it which isn't happening 
![image](https://user-images.githubusercontent.com/68808783/171647692-ebf97550-2180-4ead-891d-2f6e90512a91.png)

What it should be like is this, 
![image](https://user-images.githubusercontent.com/68808783/171648422-04eaf9fa-9e93-43c3-a9fe-e0a9096e9bf4.png)

So whenever any of the windows is resized, bar tab is resized along with it and it aligned like this:
![image](https://user-images.githubusercontent.com/68808783/171648689-daa5da4c-d974-4637-a77b-4c831fea17c5.png)

This happens by default with https://dwm.suckless.org/patches/bartabgroups/ but not with the flexipatch version.

**Comment by bakkeby** [comment]
Ah yes it would not do that in dwm-flexipatch. For all intensive purposes they are different patches.

In a traditional bar the bartabgroups patch can do that because the position of the window titles is hardcoded to be where it is and as such it can calculate where that master / stack split would appear on the bar.

In dwm-flexipatch the bar uses bar modules, which means that each segment of the bar can be moved around and positioned where desired, and the module that draws the segment is only concerned about the width given to it - not what is around it. As such it wouldn't make much sense to determine the size of the windows based on the master / stack split. Instead the size of the master title vs the size of the stack title(s) is determined by the `mfact` value.
