### ISSUE TITLE
Please add shift tools patch

### ISSUE THREAD

**Issue by taep96** [bakkeby/dwm-flexipatch#270]
Hi, could you please add the [shift tools](https://dwm.suckless.org/patches/shift-tools/) patch

**Comment by bakkeby** [comment]
It is more like a collection of patches / functions rather than a single patch though, some of which are already included.

I'll have a look but I'll likely end up adding them individually.

**Comment by bakkeby** [comment]
@explosion-mental I noticed a bug in your `shifttagclients` function.

https://dwm.suckless.org/patches/shift-tools/shift-tools.c

```c
    for (c = selmon->clients; c; c = c->next)
        if (!(c->tags))
            tagmask = tagmask | c->tags;
```

The `!(c->tags)` means that the tagmask will inevitably be 0 here. You should just remove the if statement entirely. 

It comes from de-patching the (annoying) scratchpads patch which has this:

```c
    for (c = selmon->clients; c; c = c->next)
        if (!(c->tags & SPTAGMASK))
            tagmask = tagmask | c->tags;
```
ref. https://dwm.suckless.org/patches/shift-tools/shift-tools-scratchpads.c

**Comment by bakkeby** [comment]
@taep96 I have added the extra functions from the shift-tools patch now, should be compatible with all the other patches but do let me know if you find any issues. Closing this.

**Comment by explosion-mental** [comment]
> The !(c->tags) means that the tagmask will inevitably be 0 here. You should just remove the if statement entirely.

Thanks

> If that is to be the case then you'd want to skip the selected client when calculating the tagmask.

I don't understand. What I meant is that if there are no clients, on any tag, then just `shiftview` (since `shiftviewclients` will do nothing). By using `c != selmon->sel` this will work only once and then it will `shiftviewclients` back to that client, since it's the only client and it doesn't have the focus.

**Comment by explosion-mental** [comment]
update: https://git.suckless.org/sites/commit/8ddf8523e8eec6b94f905c895a62c5d5b266af04.html

**Comment by bakkeby** [comment]
Makes perfect sense refactoring logic out to a shift function. 

What I meant regarding the selected client was specifically in relation to shifttagclients.

If you start dwm, go to tag 6, open a window, then do the keybinding for shifttagclients - then it will find the selected client that is on tag 6 and it will shift until it arrives at tag 6 again and nothing will have changed. By skipping the selected client the tagmask variable will be 0 and it will behave just like shifttag does (as advertised on the suckless page).

Similarly let's say that you have two clients, one that resides on tag 2, and the other that resides on tag 3, 5 and 8. If the view is on tag 5 then you'd expect that shifttagclients would place the selected client on tag 2 along with the other one, rather than ending up alone on tag 3 or tag 8. Skipping the selected client when calculating the tagmask variable fixes this as well.

**Comment by explosion-mental** [comment]
Oh I C good catch
