### ISSUE TITLE
Add the Bar Option patches like Active Tag Indicator.

### ISSUE THREAD

**Issue by chadify** [bakkeby/dwm-flexipatch#278]
Currently, in patches.def.h these are shown as N/A. It'd be greatly appreciated if you add the ability to incorporate these patches into dwm.

**Comment by bakkeby** [comment]
These were options in the past, as per the original patches, see the old 1.0 branch for example:
https://github.com/bakkeby/dwm-flexipatch/tree/dwm-flexipatch-1.0

They are now not applicable (N/A) as patch options as they are baked into tagicons, not because the patch itself has been removed. 

https://github.com/bakkeby/dwm-flexipatch/blob/df5eba3f8fc32c3843fe6ba35b18743312ed27ed/config.def.h#L414-L418
