### ISSUE TITLE
window don't focus automatically

### ISSUE THREAD

**Issue by romariorobby** [bakkeby/dwm-flexipatch#281]
when you enable `NOBORDER_PATCH` and restart with `RESTARTSIG_PATCH` seems that window unable to focus back, i had to spawn another window or either close the window. is there a way to fix this? Thanks

**Comment by romariorobby** [comment]
kkkkkk21

**Comment by romariorobby** [comment]
Thanks for quick response. 
Yeah, i noticed that too,i think its nothing to do with noborder patch
but here the way i reproduce this issue:
- open any apps
- restart with `RESTARTSIG` command (MOD+Shift+Ctrl +q)

list of patches i enabled: 
```
#define BAR_LTSYMBOL_PATCH 1
#define BAR_STATUS_PATCH 1
#define BAR_SYSTRAY_PATCH 1
#define BAR_TAGS_PATCH 1
#define BAR_WINTITLE_PATCH 1
#define BAR_TITLE_LEFT_PAD_PATCH 1
#define CYCLELAYOUTS_PATCH 1
#define MONITOR_RULES_PATCH 1
#define NOBORDER_PATCH 1
#define PERTAG_PATCH 1
#define PERTAG_VANITYGAPS_PATCH 1
#define PERTAGBAR_PATCH 1
#define RESTARTSIG_PATCH 1
#define VANITYGAPS_PATCH 1
#define FIBONACCI_DWINDLE_LAYOUT 1
#define FIBONACCI_SPIRAL_LAYOUT 1
#define TILE_LAYOUT 1
#define MONOCLE_LAYOUT 1
```


https://user-images.githubusercontent.com/40323094/179521772-d94eb748-e49b-4586-bfe0-b3be1762a387.mp4

**Comment by romariorobby** [comment]
Did you tried spawn just a single window? multiple window just works as expected.

Its also happen with st and alacritty even with `pkill -HUP dwm` but with st, the restart didn't fire up quickly, though still freeze afterward.

https://user-images.githubusercontent.com/40323094/179554499-f7bacc2e-6d16-4073-a182-346a32431b03.mp4

**Comment by bakkeby** [comment]
That is pretty odd. I did try a single window yes and could not replicate. 

If you disable the seamless restart patch, open a single window on tag 1, then restart, does the issue still happen?

**Comment by romariorobby** [comment]
Yess indeed, I didn't enable seamless restart patch at all.

Well, i tried to use vanilla dwm latest version earlier with only restartsig patch. still have the same issue. i'm wondering if this are the default behaviour? :smile:

**Comment by bakkeby** [comment]
I don't think so. I suspect something else is interfering. 

Would be interesting if you are also able to reproduce this issue in Xephyr - I use this a lot for testing changes.

**Comment by romariorobby** [comment]
Oh well apparently, i couldn't reproduce this in Xephyr. what would be the cause then?  maybe you could help me, what should i investigate. that would be helpful. I'll try on different machine tomorrow though.  Thanks for helping me out.

https://user-images.githubusercontent.com/40323094/179580632-c3087675-efc0-47bd-bb33-a2c8c18696d0.mp4

**Comment by bakkeby** [comment]
Since you can't replicate the issue in Xephyr I think that suggests that it isn't an issue with the software (dwm), but perhaps caused by something else. I haven't heard anyone else reporting issues like this. 

A stab in the dark but you could try to check the Xorg logs for clues.

I don't think that it should make any difference but do you use a login/display manager or do you start your window manager through startx?

**Comment by romariorobby** [comment]
i used lightdm for my display manager. 

Yeah i should close this issue now. I appreciate your help. Thanks.

**Comment by bakkeby** [comment]
I'd still be interested to know what the root cause was. Looking at the videos it is clear that the window is managed by the window manager and that it gets input focus (given that you see the random characters you typed shows up later when you open another terminal).

The window graphics is not drawn / updated, however. I wonder if a resize is what triggers it to come back.

I'd expect that if you try to resize the frozen window using the mouse that it would become responsive again.

**Comment by bakkeby** [comment]
Ah right, I can replicate the issue using xcompmgr. A compositor issue crossed my mind but I didn't think that would be the case as I didn't see any transparency effects in your videos.
