### ISSUE TITLE
scratchpads

### ISSUE THREAD

**Issue by plum** [bakkeby/dwm-flexipatch#29]
Hello Stein,
I've tried numerous patches all working without problem, with just one query concerning scratvchpads. There are three alternitves in flexipatch. Two are variations of the same patch, I believe;  SCRATCHPAD_PATCH and SCRATCHPAD_KEEP_POSITION_AND_SIZE_PATCH, which I beleive both use the included 3 'scratchpad' key mappings in config.def.h, along with 3 user-defined scratchpads, bound to MOD1 xkb_grave.

I haven't been able to get these to work, even after trying different key mappings subsituting the given xkb_grave for, e.g. xkb_apostrophe, and xkb_minus, which should work on my keybopard setup.
All other key mappings work, for all other patches I've tried, inlcuding for the SCRATCHPAD_ALT_1_PATCH (i.e xkb_minus, xkb_=), which works fine as a scratchpad in dwm_flexipatch.
My preference is for the 'named' scratchpads thoughi due ot their persistence, not the _ALT_PATCH. And, scratchpads are particlulary neat and useful to me (important).

So, I wonder if you can confirm they are working  as applied by flexipatch, and if they are, why I ma be getting this non-functionality.

==== btw. I'm enjoying use of your flexipatch. It has helped me explore functionality although I'm a 1 year long user of dwm with patches.

Kind Regards,
John

**Comment by bakkeby** [comment]
Hi John,

I have never really used these scratchpad patches in practice. Personally I just launch a minimalistic kwrite window for quick notes and so far I haven't had a specific need for an application that I repeatedly hide/unhide in my workflow.

That said here is a breakdown of the scratchpad patches in the dwm-flexipatch build:

**SCRATCHPAD_PATCH**
There's the original https://dwm.suckless.org/patches/scratchpad/ that I did have in my build in the past. It was specifically to open a terminal to do some quick typing, which seems counter-intuitive to me. I eventually removed this in favour of the multiple scratchpad patch by Christian Tenllado, ref.
https://lists.suckless.org/hackers/2004/17205.html

This lets you specify as many scratchpads as you want, and have one keybinding per scratchpad.

**SCRATCHPAD_KEEP_POSITION_AND_SIZE_PATCH**
As you say, this is merely an alteration of the above patch. Avoids the window always going back to the original position whenever you open/show it. Needs both patches to be enabled of course.

Personally this would be my choice.

**SCRATCHPAD_ALT_1_PATCH**
This is a different way of thinking when it comes to scratchpads. I think the idea here is that you open an application, let's say gedit, then you hide it by pushing it to the scratchpad, then you can reveal and hide it again. The twist here is that scratchpads are chained, so you could hide a second window, then a third. So in order to show the gedit window you'd have to first reveal the third window, then the second, then once more and the first window (gedit) would show.

I think it all depends on how you use it and how it fits into your workflow.

I see that there is an update to this patch so I'll have to have a look at some point if I need to update my build.
https://github.com/GasparVardanyan/dwm-scratchpad/blob/master/dwm-scratchpad-20200510-f09418b.diff

-----

Both patches should work just fine. XK_grave would be the backtick (`) button, but changing this should be just fine.

Just make sure you change the scratchpad configuration to something that you actually use, the default example settings that comes with the patch looks like this:
```
const char *spcmd1[] = {"st", "-n", "spterm", "-g", "120x34", NULL };
const char *spcmd2[] = {"st", "-n", "spfm", "-g", "144x41", "-e", "ranger", NULL };
const char *spcmd3[] = {"keepassxc", NULL };
static Sp scratchpads[] = {
   /* name          cmd  */
   {"spterm",      spcmd1},
   {"spranger",    spcmd2},
   {"keepassxc",   spcmd3},
};
```
Unless you have the applications of `st`, `ranger` and `keepassxc` then it wouldn't work.

> _btw. I'm enjoying use of your flexipatch. It has helped me explore functionality although I'm a 1 year long user of dwm with patches_

Ha, I've been using dwm for about the same amount of time then :D

\
Thanks,

-Stein

**Comment by plum** [comment]
Thank you for your response Stein. I agree with your choice of personal
choices for scratchpad, the keeping same size andposition, and multiple
named. 

Yes, the grave is a backtick, which I do not have, so I did change it ,
as mentioned.

I did check the programmes specified in the s commands for each
scratchpad, changing them accordingly. I shall have to  investigate
further, I think, now htat I know how things are. It may still be
trivial...

== btw then you're way ahead of me in prgramming! (:  This project is almost
stupendous! I suspect it will be aorund for a long time and adopted into
Suckless in some way..... I wonder if you learnt programming in a
course. Or perhaps self-taught... well probably both!

**Comment by bakkeby** [comment]
> _I suspect it will be aorund for a long time and adopted into Suckless in some way....._

Heh, I doubt that. This is pretty much as anti-suckless as it can get.

> _I wonder if you learnt programming in a course. Or perhaps self-taught... well probably both!_

You only learn so much in a course. I have prior programming experience in a few other languages, but the only C I know I've learnt by tinkering with dwm.

**Comment by plum** [comment]
Oh, I know what you mean I think, in terms of user approach to patching.
But the result is suckless code, with user preferences,  to use! I
wonder if it could be incorporated philosphically.. Perhaps then, it
would be wise not to encourage!!! 

It takes along time to employ more several patches together, depending
on order and patch, particulalry for testing out purposes... mmmmmm. 
Seems a good thing to me, within limits though, if a user is to take fair responsibility.

Appreciated.
John

**Comment by bakkeby** [comment]
I have updated Gaspar Vardanyan's scratchpad patch now, it was pretty minor.

**Comment by bakkeby** [comment]
Marking as closed.

**Comment by plum** [comment]
Thank you for the notification Mr Bakkeby. I shall check out the update. 
I have been using your flexipatch  daily with great results. It has given me the opportunity to try out easily  combinations that might suit me; I  hit upon a suitable result fairly quickly employing about seven patches (one or two may be 'dual-option combinations'... a single patch really), and which is working well.  During that time I have been able to really use it productively, with increasing ease in short cuts and functionality. Prior to flexipatch I had managed to employ just three patches.  Now, I'll switch to Gaspar's scratchpad which I would prefer, I beleive.
John

**Comment by CSpencerND** [comment]
Sorry for commenting on a closed issue. I couldn't find and open one that relates to my situation and I didn't think it was appropriate to make a new one.

I'm having an issue when I try to toggle a scratchpad off, it instead creates a new one on top of the existing one.
So it's acting as create instead of toggle.

**Comment by bakkeby** [comment]
@CSpencerND yes that's a common issue and it has to do with client rules not applying to the scratchpad window being launched.

The general logic being that hitting a scratchpad keybinding the patch / code will search for a client associated with that scratch key, and if not found then it will spawn a new window by executing a command. 

When the new window comes up there should be a client rule that identifies that window as a particular scratchpad window and sets the scratch key for that client so that this window will be found the next time you hit that scratchpad keybinding. 

If there is no client rule that matches doing this then the keybinding will just spawn new windows as you describe.

**Comment by CSpencerND** [comment]
I'm missing something?
`const char *spcmd0[] = { "st", "-c", "scratchpad", "-t", "spterm", "-g", "120x34", NULL };`
`RULE(.title = "spterm", .tags = SPTAG(0), .isfloating = 1)`
```
static Sp scratchpads[] = {
        {"spterm",    spcmd0},
};
```
`{ MODKEY,  XK_apostrophe,  togglescratch,  {.ui = 0 } },`

**Comment by CSpencerND** [comment]
Forgot one detail. It works as expected for the first one, not the other three.

**Comment by bakkeby** [comment]
@CSpencerND maybe it has something to do with that the other three use -e and executes things like btop, which may mean that running btop results in that program overriding the window title you set for st via the command line option -t.

Perhaps try to set the instance or class of st instead and have your rules match on that instead of the title.

**Comment by CSpencerND** [comment]
@bakkeby Ok, thanks. I truly appreciate all your help.

**Comment by CSpencerND** [comment]
@bakkeby I'm sorry, I just don't get it. I didn't have this problem with the vanilla dwm version before I switched to flexipatch. I tried everything I could think of and it behaves the same no matter what flags I use to launch the terminals, and no matter which rules I use.

**Comment by bakkeby** [comment]
@CSpencerND ok so what does your commands and rules look like if you are matching on class rather than title?

**Comment by CSpencerND** [comment]
@bakkeby  I looked at the `applyrules` function and thought about how `strstr()` works, so I changed the classes of the scratchpads to be completely unique and now they function properly :)

**Comment by CSpencerND** [comment]
The only oddity I didn't mention before is with shiftview. After hiding the scratchpad, if I shiftview to the left the pad shows up on a tag.

**Comment by CSpencerND** [comment]
> @CSpencerND ok so what does your commands and rules look like if you are matching on class rather than title?
`const char *spcmd0[] = { "st", "-c", "basic", "-g", "120x34", NULL };`
`RULE(.class = "basic",   .tags = SPTAG(0), .isfloating = 1)`

**Comment by CSpencerND** [comment]
> @CSpencerND ok so what does your commands and rules look like if you are matching on class rather than title?

`const char *spcmd0[] = { "st", "-c", "basic", "-g", "120x34", NULL };`
`RULE(.class = "basic",   .tags = SPTAG(0), .isfloating = 1)`

**Comment by CSpencerND** [comment]
I replaced the `shiftview()` function inside `patch/shiftview.c` with the one from https://dwm.suckless.org/patches/shift-tools/shift-tools-scratchpads.c and it works perfectly.

**Comment by bakkeby** [comment]
Yes that is the annoying thing with that scratchpads patch - it has compatibility issues with so many other patches as it reserves extra tags for the scratchpads. 

In hindsight the named scratchpads patch is the better choice.

**Comment by bakkeby** [comment]
@CSpencerND I included that compatibility fix for the shiftview patch. Thanks for reporting.

and for plum, sorry for the spam 📬

**Comment by CSpencerND** [comment]
@bakkeby I love this shxt even if it drives me crazy ☺️
