### ISSUE TITLE
need some help in fixing dwm.c for the statuscmd-signal and systray patch.

### ISSUE THREAD

**Issue by apoorv569** [bakkeby/dwm-flexipatch#30]
im sorry if this not the right place to ask for help for this but im facing a issue where the `dwm-systray-6.2.diff` patch and `dwm-statuscmd-signal-6.2.diff` patch are not able merge properly in dwm.c as 
the `dwm-systray-6.2.diff` patch want me to do this- 
```
@@ -439,7 +475,7 @@ buttonpress(XEvent *e)
 			arg.ui = 1 << i;
 		} else if (ev->x < x + blw)
 			click = ClkLtSymbol;
-		else if (ev->x > selmon->ww - TEXTW(stext))
+		else if (ev->x > selmon->ww - TEXTW(stext) - getsystraywidth())
 			click = ClkStatusText;
 		else
 			click = ClkWinTitle;
```
and the `dwm-statuscmd-signal-6.2.diff` wants me to do this 
```
@@ -439,9 +445,26 @@ buttonpress(XEvent *e)
 			arg.ui = 1 << i;
 		} else if (ev->x < x + blw)
 			click = ClkLtSymbol;
-		else if (ev->x > selmon->ww - TEXTW(stext))
+		else if (ev->x > (x = selmon->ww - TEXTW(stext) + lrpad)) {
 			click = ClkStatusText;
-		else
+
+			char *text = rawstext;
+			int i = -1;
+			char ch;
+			dwmblockssig = 0;
+			while (text[++i]) {
+				if ((unsigned char)text[i] < ' ') {
+					ch = text[i];
+					text[i] = '\0';
+					x += TEXTW(text) - lrpad;
+					text[i] = ch;
+					text += i+1;
+					i = -1;
+					if (x >= ev->x) break;
+					dwmblockssig = ch;
+				}
+			}
+		} else
 			click = ClkWinTitle;
```
im not sure how to combine this line `else if (ev->x > selmon->ww - TEXTW(stext) - getsystraywidth())` and `else if (ev->x > (x = selmon->ww - TEXTW(stext) + lrpad)) {` as i want to use both the systray and i need statuscmd-signal for the dwmblocks for clickable status bar.
i have it like this right now
```
	//	else if (ev->x > selmon->ww - TEXTW(stext) - getsystraywidth())
	//		click = ClkStatusText;
		else if (ev->x > (x = selmon->ww - TEXTW(stext) + lrpad)) {
			click = ClkStatusText;
```

i have comment out the first to lines because status bar wont recognize clicks if that line is enabled. after commenting out im able to click on statusbar just fine but having some positioning issues like the from left to right clock battery and volume modules appear on statusbar to click on volume i need to click on battery because i have 1 icon in the systray so its causing positioning issues. maybe im wrong. i can send u my configs and screenshots if necessary.
BTW im using everything vanilla patched everything myself not using flexipatch.

**Comment by bakkeby** [comment]
When it comes to patches systray + statuscmd is fairly straightforward to combine. It gets a lot more complicated if you want to include the status2d patch for example. 

The main clue here is not what the two patches does, but what the original code does.
```
else if (ev->x > selmon->ww - TEXTW(stext))
	click = ClkStatusText;
```
which reads as if the mouse click event x position is greater than the width of the monitor minus the width of the status text, then we are clicking on the status text.

This means that the status text is positioned on the far right on the bar (this is obvious right as you can simply see it, but talking from a code perspective here).

The systray patch changes this to:
```
else if (ev->x > selmon->ww - TEXTW(stext) - getsystraywidth())
	click = ClkStatusText;
```
The only change here is that it also takes the width of the systray into account, this to make sure that we find the right start position of the status text (otherwise a portion of the left hand of status text, about the width of the systray, would not be clickable.

The statuscmd patch changes the original code to:
```
else if (ev->x > (x = selmon->ww - TEXTW(stext) + lrpad)) {
...
```
It adds lrpad, which is not obvious, but in practice it means that we just want to take the exact length of the status text width into account here. This logic comes from that the TEXTW macro includes rlpad and we just want to adjust for that.
```
#define TEXTW(X)                (drw_fontset_getwidth(drw, (X)) + lrpad)
```

So the lrpad is trivial, but the primary concern here is the _assignment_ of this position to the `x` variable.
```(x = selmon->ww - TEXTW(stext) + lrpad)```

This is the main reason why your commented out line does not work. Combining these is as simple as taking the width of the systray into account when finding this start position.
```
else if (ev->x > (x = selmon->ww - TEXTW(stext) + lrpad - getsystraywidth())) {
...
```
Note that this assignment will conflict with the awesomebar patch as that also relies on the x position, so if you intend on taking that then you can move the assignment into the if statement (with a minor performance cost of calculating the text width twice of course).
```
else if (ev->x > selmon->ww - TEXTW(stext) + lrpad - getsystraywidth()) {
	x = selmon->ww - TEXTW(stext) + lrpad - getsystraywidth();
```

As far as I recall that's all really for this integration. Many words for a simple solution.

**Comment by apoorv569** [comment]
> When it comes to patches systray + statuscmd is fairly straightforward to combine. It gets a lot more complicated if you want to include the status2d patch for example.
> 
> The main clue here is not what the two patches does, but what the original code does.
> 
> ```
> else if (ev->x > selmon->ww - TEXTW(stext))
> 	click = ClkStatusText;
> ```
> 
> which reads as if the mouse click event x position is greater than the width of the monitor minus the width of the status text, then we are clicking on the status text.
> 
> This means that the status text is positioned on the far right on the bar (this is obvious right as you can simply see it, but talking from a code perspective here).
> 
> The systray patch changes this to:
> 
> ```
> else if (ev->x > selmon->ww - TEXTW(stext) - getsystraywidth())
> 	click = ClkStatusText;
> ```
> 
> The only change here is that it also takes the width of the systray into account, this to make sure that we find the right start position of the status text (otherwise a portion of the left hand of status text, about the width of the systray, would not be clickable.
> 
> The statuscmd patch changes the original code to:
> 
> ```
> else if (ev->x > (x = selmon->ww - TEXTW(stext) + lrpad)) {
> ...
> ```
> 
> It adds lrpad, which is not obvious, but in practice it means that we just want to take the exact length of the status text width into account here. This logic comes from that the TEXTW macro includes rlpad and we just want to adjust for that.
> 
> ```
> #define TEXTW(X)                (drw_fontset_getwidth(drw, (X)) + lrpad)
> ```
> 
> So the lrpad is trivial, but the primary concern here is the _assignment_ of this position to the `x` variable.
> `(x = selmon->ww - TEXTW(stext) + lrpad)`
> 
> This is the main reason why your commented out line does not work. Combining these is as simple as taking the width of the systray into account when finding this start position.
> 
> ```
> else if (ev->x > (x = selmon->ww - TEXTW(stext) + lrpad - getsystraywidth())) {
> ...
> ```
> 
> Note that this assignment will conflict with the awesomebar patch as that also relies on the x position, so if you intend on taking that then you can move the assignment into the if statement (with a minor performance cost of calculating the text width twice of course).
> 
> ```
> else if (ev->x > selmon->ww - TEXTW(stext) + lrpad - getsystraywidth()) {
> 	x = selmon->ww - TEXTW(stext) + lrpad - getsystraywidth();
> ```
> 
> As far as I recall that's all really for this integration. Many words for a simple solution.

its working now. thank you for explaining what the code is doing. :D

**Comment by apoorv569** [comment]
its working now. thank you for explaining what the code is doing. :D
