### ISSUE TITLE
why not xresources patch?

### ISSUE THREAD

**Issue by tienbuigia** [bakkeby/dwm-flexipatch#316]
I'm asking this because I want to change font by just edit the xresources file.

Is there any reason you choose xrdb patch instead of xresources one?

## happy so far
I've been using flexipatch for so long and really happy with it.
Really thanks for your works bakkeby.

**Comment by bakkeby** [comment]
As a question this might have been better placed under the Q&A topic in the discussions section.

The underlying reason would be that only the xrdb patch existed when this was originally merged, the xresources one came later.

The follow-up question would be why the xrdb patch was never upgraded to the xresources patch.

This is subjective but I don't quite see it as an upgrade; each patch provides their own distinct (but partially overlapping) functionality.

The xrdb patch:
   - loads colours from xresources
   - can reload colours dynamically during runtime without the need to restart the window manager

The xresources patch:
   - can load strings from xresources
   - can load integer values from xresources
   - can load float values from xresources
   - only works during the initial load, can't refresh during runtime

As per the patch you have that the xresources patch loads colours as well as `borderpx`, `snap`, `showbar`, `topbar`, `nmaster`, `resizehints` and `mfact`. 

This clearly has an appeal in that one can use Xresources like a configuration file without the need to recompile dwm.

It wouldn't be particularly difficult to take the xresources patch, or to provide both options for that matter.

Conceptually I find it easier to say that only colours are loaded from Xresources. The main reason why I have never incorporated the xresources patch is because I foresee a plethora of issues being raised in relation to it.

Here are some plausible examples:
   -  "I change the font in config.h and recompile - but it always looks the same" (due to font setting in Xresources overriding it)
   - requests to be able to reload settings dynamically like how the xrdb patch can reload colours on the fly
   - expectations that it should be possible to change every and any setting via Xresources - like layouts, keybindings and client rules - given that the [patch page](https://dwm.suckless.org/patches/xresources/) says "that it can handle any kind of setting as opposed to only color settings"
   - dwm crashing due to having an invalid resource string in Xresources (this can also happen with colour strings mind you)

**Comment by tienbuigia** [comment]
Sorry for putting this on issues section, my noob mistake.

Thanks your detailed answer.
I'm using xresources patch right now and too lazy to comeback and test out so I ask for more.

Can I add more values to this block code to make dwm loads more values just like xresources?

```c
if (xrdb != NULL) {
        XRDB_LOAD_COLOR("dwm.normbordercolor", normbordercolor);
        XRDB_LOAD_COLOR("dwm.normbgcolor", normbgcolor);
        XRDB_LOAD_COLOR("dwm.normfgcolor", normfgcolor);
        XRDB_LOAD_COLOR("dwm.selbordercolor", selbordercolor);
        XRDB_LOAD_COLOR("dwm.selbgcolor", selbgcolor);
        XRDB_LOAD_COLOR("dwm.selfgcolor", selfgcolor);
      }
```

**Comment by bakkeby** [comment]
No you would need more changes like what was implemented in the xresources patch. The xrdb patch uses a macro (for no particular good reason) and this macro is specific for loading colour strings, so you can't use that to override other values (like fonts).
