### ISSUE TITLE
raise or spawn patch

### ISSUE THREAD

**Issue by duarm** [bakkeby/dwm-flexipatch#328]
Similar to awesome wm's raise_or_spawn, a new command like spawn which would check if there's already a window open which contains the command, if so, it brings that window to the current tag focusing on it, otherwise it spawns the window normally.

there's an implementation here https://gist.github.com/ivoarch/4107047, but it's not that good since it fails when the command launches other programs, like electron does. Not sure the best way to implement this.

**Comment by bakkeby** [comment]
Unless you are specifically configuring scratchpads my general recommendation is to keep window management specific keybindings in the dwm configuration and to keep application launching keybindings separately e.g. using [sxhkd](https://github.com/baskerville/sxhkd).

The benefit of this is that if you are trying out any other window manager or different builds of dwm then you can always open the same programs using the same keybindings provided that `sxhkd` is running. E.g. you can log into openbox and not scratch your head trying to figure out how to open a terminal.

You can of course use such a `runorraise` function in dwm if you want to. You can even dump that function straight in your config.h file directly and use it the keybindings.

As for dwm I'd rather recommend just using the [focusonnetactive](https://dwm.suckless.org/patches/focusonnetactive/) patch and using `xdo` to activate the program if it exists and to start it otherwise. Here is an example keybinding for `sxhkd`:

```
super + F8
    xdo activate -N firefox || firefox
```

**Comment by duarm** [comment]
I'll try your dwm solution when I have time, and close this, thanks

**Comment by duarm** [comment]
xdo solution worked quite well, thanks
