### ISSUE TITLE
mysterious bar area with nothing in it

### ISSUE THREAD

**Issue by apprehensions** [bakkeby/dwm-flexipatch#335]
![20230202_204951_sc](https://user-images.githubusercontent.com/47404953/216402792-f3e008d0-50c7-4dd4-9e53-dd8e561284bf.png)
see that empty area between the tags and the window?
```c
#define BAR_AWESOMEBAR_PATCH 1
#define BAR_DWMBLOCKS_SIGUSR1_PATCH 0
#define BAR_FANCYBAR_PATCH 1
#define BAR_LTSYMBOL_PATCH 1
#define BAR_TABGROUPS_PATCH 0
#define BAR_STATUS_PATCH 1
#define BAR_STATUSBUTTON_PATCH 0
#define BAR_STATUS2D_PATCH 0
#define BAR_SYSTRAY_PATCH 1
#define BAR_TAGS_PATCH 1
#define BAR_UNDERLINETAGS_PATCH 0
#define BAR_WINICON_PATCH 1
#define BAR_WINTITLE_PATCH 1
#define BAR_TITLE_RIGHT_PAD_PATCH 0
#define BAR_TITLE_LEFT_PAD_PATCH 1

/**
 * Bar options
 */
#define BAR_BORDER_PATCH 0
#define BAR_EWMHTAGS_PATCH 1
#define BAR_HEIGHT_PATCH 1
#define BAR_HIDEVACANTTAGS_PATCH 0
#define BAR_HOLDBAR_PATCH 0
#define BAR_STATUSALLMONS_PATCH 1

/* This patch allows client windows to be hidden. This code was originally part of awesomebar,
 * but has been separated out so that other bar modules can take advantage of it.
 * Both awesomebar and bartabgroups patches depend on this patch and it will be auto-enabled
 * during compile time if it is needed. Note that if using flexipatch-finalizer this must be
 * explicitly enabled.
 * https://github.com/bakkeby/patches/blob/master/dwm/dwm-barmodules-wintitleactions-6.2.diff
 */
#define BAR_WINTITLEACTIONS_PATCH BAR_AWESOMEBAR_PATCH || BAR_TABGROUPS_PATCH || BAR_FLEXWINTITLE_PATCH

/***
 * Other patches
 */
#define ALWAYSCENTER_PATCH 1
#define CFACTS_PATCH 1
#define CYCLELAYOUTS_PATCH 1
#define DECORATION_HINTS_PATCH 1
#define FAKEFULLSCREEN_CLIENT_PATCH 1
#define FOCUSDIR_PATCH 1
#define FOCUSURGENT_PATCH 1
#define FOCUSONNETACTIVE_PATCH 1
#define MONITOR_RULES_PATCH 1
#define NAMETAG_PREPEND_PATCH 0
#define NET_CLIENT_LIST_STACKING_PATCH 1
#define NOBORDER_PATCH 1
#define NODMENU_PATCH 1
#define ONLYQUITONEMPTY_PATCH 1
#define PERTAG_PATCH 1
#define PERTAGBAR_PATCH 1
#define PLACEMOUSE_PATCH 1
#define PUSH_NO_MASTER_PATCH 0
#define RESTARTSIG_PATCH 1
#define SEAMLESS_RESTART_PATCH 1
#define STEAM_PATCH 1
#define SWALLOW_PATCH 1
#define TAGMONFIXFS_PATCH 1

/**
 * Layouts
 */
#define TILE_LAYOUT 1
#define MONOCLE_LAYOUT 0
```
```c
static const BarRule barrules[] = {
	/* monitor      alignment        widthfunc         drawfunc         clickfunc  */
	{ -1,        0, BAR_ALIGN_LEFT,  width_tags,       draw_tags,       click_tags,       NULL,  NULL },
//	{ -1,        0, BAR_ALIGN_LEFT,  width_ltsymbol,   draw_ltsymbol,   click_ltsymbol,   NULL,  NULL },
	{ statusmon, 0, BAR_ALIGN_RIGHT, width_status,     draw_status,     click_status,     NULL,  NULL },
	{ -1,        0, BAR_ALIGN_RIGHT, width_systray,    draw_systray,    click_systray,    NULL,  NULL },
	{ -1,        0, BAR_ALIGN_NONE,  width_awesomebar, draw_awesomebar, click_awesomebar, NULL,  NULL },
};
```

**Comment by bakkeby** [comment]
It is caused by this toggle:
```c
#define BAR_TITLE_LEFT_PAD_PATCH 1
```
You can disable that and the gap should go away.

Why that is enabled by default though I honestly don't remember. Most likely it shouldn't be and I probably ought to disable that.

---

As for why this exists.

In earlier iterations of barmodules (like the one used in dwm-flexipatch) the left and right padding to neighbouring modules was controlled by each individual module. For most modules this is fine, but it causes some issues depending on how certain modules are arranged.

If you have a window title module that takes up the entire bar or is touching one of the edges then it will look best if the window title is drawn all the way to the edge of the bar. As such the module does not have any padding by default (or shouldn't have, anyway). But if the window title touches another module then if it can look a bit jarring if it touches it. 

An example from stock dwm shows the window title being crammed up against the status.
![image](https://user-images.githubusercontent.com/1438008/216435802-7ebadf06-45e2-4c4f-a175-20aa4ad6ac62.png)

In such cases it may be useful to have a bit of padding between the window title and the other module, which is where the two toggles comes in.

Another example of this is padding for the status and padding for the systray resulting in an extra large gap.

In later iterations of barmodules this was replaced by having the left and right padding for each module available directly in the barrules array / config at the cost of adding complexity when it comes to configuring the bar.

These changes were never backported into dwm-flexipatch because:
   - there is relatively little to gain compared to the effort needed to make this work for all affected patches and 
   - such changes would break the config for anyone updating and
   - it doesn't really help the main goal of this project

**Comment by apprehensions** [comment]
thx
