### ISSUE TITLE
How do I query the current monitor?

### ISSUE THREAD

**Issue by UtkarshVerma** [bakkeby/dwm-flexipatch#341]
I'm using a multi-monitor setup and want to write a wrapper script for dmenu so that it always launches in the screen focused by dwm. So far, I could not find any EWMH tag exposed by dwm to query that information.

I found this [thread on reddit](https://www.reddit.com/r/suckless/comments/k7806r/querying_active_monitor_in_dwm/), and it recommends using dwm-ipc, but I would like to know if something could be done without it.

Can we modify DWM to hint which screen it is currently focusing on? It would be nice if that number corresponds to `xrandr`.

**Comment by bakkeby** [comment]
A bare dwm uses a variable `dmenumon` to pass the current monitor to dmenu via the `-m` command line option.

In config.h

```c
static char dmenumon[2] = "0"; /* component of dmenucmd, manipulated in spawn() */
static const char *dmenucmd[] = { "dmenu_run", "-m", dmenumon, "-fn", dmenufont, "-nb", col_gray1, "-nf", col_gray3, "-sb", col_cyan, "-sf", col_gray4, NULL };
```

```c
void
spawn(const Arg *arg)
{
	if (arg->v == dmenucmd)
		dmenumon[0] = '0' + selmon->num;
...
```
https://git.suckless.org/dwm/file/dwm.c.html#l1651

This hardcoded functionality means that users can't just get rid of dmenu from the config - they have to edit the source code as well if they want to remove dmenu. There used to be a patch called `nodmenu` which removes that variable, but this has since been removed from the patches page by the author.

dmenu has xinerama support and is perfectly able to work out on its own what monitor has focus based on what window has focus, and if no window has focus then it is based on the position of the mouse cursor.

One exception to this is if you move focus between screens using keybindings and there are no visible clients on the screen that gets focus, then the window that has focus will remain on the previous screen. It is possible to address this by giving input focus to the bar window if there are no visible clients on a monitor.

----

When it comes to dwm-flexipatch then it should generally work fine. If you use the `SORTSCREENS_PATCH` then you will probably want to take the `NODMENU_PATCH` as well unless you also integrate the sortscreens patch into dmenu (as the patch will change the order of the screens).

Do you have a practical case where this is not working for you using dwm-flexipatch?

**Comment by UtkarshVerma** [comment]
Oh, you're actually right about `dmenu` inferring the correct focused monitor by itself. I wanted to have `dmenu` overlap my bar completely and I wrote a wrapper script for that. Somewhere along the way, I thought I would need to pass the `-m` flag as well. However, I can see that if I don't pass anything, `dmenu` spawns on the correct monitor.

Thanks so the quick response!

**Comment by UtkarshVerma** [comment]
Haha, I found one edge case just after closing. :sweat_smile:. If mouse is on Monitor 1, and keyboard focus is moved using keybind to Monitor 2 without any windows, dmenu is opened in Monitor 1. Would it be possible to have dwm add a window hint to root window, whenever the focused monitor is changed? That way, I can simply query that hint in the wrapper script and have dmenu launched in the focused monitor.

**Comment by bakkeby** [comment]
Try with the `NODMENU_PATCH`.

https://github.com/bakkeby/dwm-flexipatch/blob/fcbe686ff250849b00da2479baf71dedc3cb0f07/dwm.c#L2075-L2080

It will put input focus on the bar which will allow dmenu to work it out. Of course if the bar is hidden then it doesn't work.

One could expose the selected monitor using a bespoke atom on the root window, but I don't think I would want to introduce that for a project like this.

**Comment by bakkeby** [comment]
Why do you use a wrapper script for this anyway? Do you have a weirdly sized or positioned bar?

**Comment by UtkarshVerma** [comment]
Thanks, it works with the NODMENU patch. I use a wrapper because my statusbar is padded, and I don't want to pass redundant flags to dmenu across all my scripts.

Here is the script, just in case:

```sh
#!/bin/sh
# dmenu wrapper to ensure that the menu overlaps the statusbar

scriptDir="${0%/*}"
binary="${0##*/}"
IFS=":"
for dir in $PATH; do
    [ "$dir" = "$scriptDir" ] && continue
    [ -x "$dir/$binary" ] && break
done
unset IFS

barGeometry="$(xwininfo -root -tree |
    grep '("dwm" "dwm")' | head -1 | awk '{ print $(NF - 1) }')"

height="${barGeometry#*x}"
height="${height%%+*}"
set -- "$@" -h "$height"

width="${barGeometry%x*}"
set -- "$@" -W "$width"

xOffset="${barGeometry#*+}"
xOffset="${xOffset%+*}"
set -- "$@" -X "$xOffset"

yOffset="${barGeometry##*+}"
set -- "$@" -Y "$yOffset"

exec "$dir/$binary" "$@"
```

**Comment by bakkeby** [comment]
Right, I'd just use the barpadding patch in that case.

**Comment by UtkarshVerma** [comment]
Yeah, I had that option but the dynamic nature of this wrapper feels better for me.
