### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by se7en-x230** [bakkeby/dwm-flexipatch#373]
I need some help.

I use a highly customized Luke's DWM build.
Now I would like to build it from scratch myself as there are excellent points in Luke's build but also some I not need.

What I struggle with are the patches.
Mainly to understand with patches
1. Fullscreen 
2. Clickable den blocks
3. Scratchpads

What I need is
1. Hide inactive tags
2. Per tag resizing
3. Fullscreen
4. dmwblocks (Luke smith)
5. Scratchpads
6. Master stack (only) layout
7. Swollow 
8. Simple gaps (no need to change them via keybindings)
9. Switch window to master side

Sorry I know this is a bit off topic

**Comment by bakkeby** [comment]
> as there are excellent points in Luke's build but also some I not need

That kind of sounds like you are aiming for something more minimal. If that is the case then you _may_ want to consider just staying on Luke's build as that that is already pretty minimal (despite the patching).

If there are some specific things that you do not need then it may be easier to de-patch (remove) that rather than starting from scratch.

Anyway, when it comes to the three patches you are struggling with; what are you having difficulties understanding with them and also which patches are you specifically referring to?

I am asking because there are several variants of those patches out there.

**Comment by se7en-x230** [comment]
> I am asking because there are several variants of those patches out there.

You hit the nail on the head. 
Sadly Luke's build is not very transparent otherwise I would have done exactly that. Remove the patches I do not need.
But as I can't figure out which one are installed in the first place, I thought I go the other way

**Comment by se7en-x230** [comment]
thanks you for looking into this
