### ISSUE TITLE
help with NODMENU

### ISSUE THREAD

**Issue by Zerogaku** [bakkeby/dwm-flexipatch#378]
I don't understand why dwm has built in configurations for dmenu if i could just edit the dmenu config itself, since i'm trying to build a config with dmenu-flexipatch i was wondering if it's ok to use NODMENU to remove those unused configurations in the config.h of dwm.

**Comment by bakkeby** [comment]
The general answer to your question is yes it is OK remove the dmenu configuration from your dwm config (because you set up the system exactly the way you want to).

----

The "no dmenu" patch is intended for those that want to remove dmenu entirely and maybe use something else like rofi for example.

A bare dwm has the following default config:

```c
static char dmenumon[2] = "0"; /* component of dmenucmd, manipulated in spawn() */
static const char *dmenucmd[] = { "dmenu_run", "-m", dmenumon, "-fn", dmenufont, "-nb", col_gray1, "-nf", col_gray3, "-sb", col_cyan, "-sf", col_gray4, NULL };
```
(this looks slightly different in dwm-flexipatch)

The `dmenumon` array is used to indicate which monitor currently has focus and the array is updated in the `spawn` function when spawning `dmenucmd`.

Besides that the command includes a series of command line arguments to set the font and various colours. The main reason for this is so that when you spawn dmenu (or rather, the `dmenu_run` shell script) then the window that pops up should have colours that matches that of the window manager to make it look more seamless.

There is nothing wrong with removing all of this and control the colours and font of dmenu via .Xresources for example.

dmenu is very capable of working out which monitor has focus. It does that by querying the X server to find out which window has focus and then works out which monitor that window resides on based on the size and position of the window. If there are no windows then it will fall back to working out which monitor the mouse cursor is on.

One side effect of removing the configuration from the dwm config is that if you have a keyboard centric workflow and you use keybindings to focus on another (empty) monitor then dmenu may appear on the wrong monitor due to the window that has focus or the position of the mouse cursor.

It is possible to work around this by giving the bar window input focus on the monitor that has focus when there are no visible clients.

This can be done in the `focus` function:

```diff
void
focus(Client *c)
{
    ...
    if (c) {
        ...
    } else {
-       XSetInputFocus(dpy, root, RevertToPointerRoot, CurrentTime);
+       XSetInputFocus(dpy, selmon->barwin, RevertToPointerRoot, CurrentTime);
        XDeleteProperty(dpy, root, netatom[NetActiveWindow]);
    }
    ...
}
```

That said; if the bar is hidden (toggled away) then dmenu can't work out which monitor the bar is on because the position of the bar is outside the monitor borders (and thus it will revert to the monitor the mouse cursor is on).

This edge case is the reason why the [nodmenu](https://git.suckless.org/sites/commit/ed68e3629de4ef2ca2d3f8893a79fb570b4c0cbc.html) patch has not been included in the main dwm.

**Comment by Zerogaku** [comment]
I see, so dwm has the built in configuration to help dmenu figure out which monitor to spawn correctly in (assuming the mouse is on the wrong monitor when the statusbar is hidden), and the dmenucmd is used to set up better defaults like font and colorscheme? I was just a little confused since I'm trying to replicate [luke smith's config](https://github.com/LukeSmithxyz/dwm/blob/master/config.h) in flexipatch and noticed that his config.h does not include dmenufont, dmenumon or dmenucmd, i suspect he applied a similar patch to NODMENU
