### ISSUE TITLE
Congrats

### ISSUE THREAD

**Issue by plasmoduck** [bakkeby/dwm-flexipatch#39]
First off congrats on this project, great job! I've forked it [here](https://github.com/plasmoduck/modwm) and made a few changes myself.

If you have the time, could you give me a quick rundown of adding a new module to patch in like [this](https://dwm.suckless.org/patches/launcher/) one for example. Creating the .c file etc 

Cheers

**Comment by plasmoduck** [comment]
Also, there is a bug when I select to use the tag powerline patch, dwm will draw 2 sets of tags, the first powerline then a normal set right after it.

**Comment by bakkeby** [comment]
I guess have a read over https://github.com/bakkeby/patches/wiki/barmodules and look at the how the bar rules are set up.

To create a new one it is easiest to have a look at existing modules, the `patch/bar_ltsymbol.c` one is pretty straightforward. You just provide three functions one giving the width of the module, one that draws the module and one that interprets button clicks. The content of these functions should be relatively easy to work out based on the launchers diff.

These three functions are then used in the bar rules which handles position etc.

> Also, there is a bug when I select to use the tag powerline patch, dwm will draw 2 sets of tags, the first powerline then a normal set right after it.

Yes I'm aware, that's kind of intentional. It's trivial to change the endif + if to an elif to not have this behaviour, but I left it there as a gotcha as you have explicitly said in your patches config that you want both tags and powerline tags in your bar. The gotcha is meant as an incentive to go and work out why it behaves like this - which would likely lead you to finding out how you can position everything on the bar as you please.

Of course if you'd prefer a traditional dwm bar then there is also the 1.0 branch

**Comment by plasmoduck** [comment]
Ahh, makes sense about the powerline. Thanks for that. I'll try to keep my fork in sync with your upstream repo.
