### ISSUE TITLE
I'm not sure if we should focus first then arrange in view function

### ISSUE THREAD

**Issue by ysl2** [bakkeby/dwm-flexipatch#390]
I have checked the offical dwm repo, in the `view()` function, first `focus()` then `arrange()`.

In your repo, they are reversed. So I'm not sure if this is correct, or this is intended to do.

https://github.com/bakkeby/dwm-flexipatch/blob/4a22fd046cdeb53899eb23f81607287244dcdfdb/dwm.c#L5002-L5007

**Comment by bakkeby** [comment]
Besides you being unsure about it, are you experiencing any particular issues due to this?

In general `focus` and `arrange` are independent of each other so the order should not really matter.

The change was intentional in relation to the `focusfollowmouse` patch where focus is given to the client where the mouse cursor is (e.g. when changing tags) rather than the most recently focused client.

In this scenario you will want to do the arrange to take place first so that clients are positioned correctly before trying to work out which window is located under the mouse cursor.

The changes were introduced in this commit:
https://github.com/bakkeby/dwm-flexipatch/commit/99f6f1b52cdd70f02d0ad902d7bfac6e2e889464

**Comment by ysl2** [comment]
Thank you. There is no any issue. I just want to confirm it :-)
