### ISSUE TITLE
Extrabar question

### ISSUE THREAD

**Issue by Zerogaku** [bakkeby/dwm-flexipatch#421]
How would I go about creating separate status bars with different modules? Would this be dependent on dwmblocks or is there already built in functionality for this?

![image](https://github.com/bakkeby/dwm-flexipatch/assets/144664603/6707f945-44bf-486a-9a6d-09a9e1d986a9)

**Comment by bakkeby** [comment]
The extrabar patch will add one more status (as in you can have two statuses).

This is based on a single status that comes through the root window name (e.g. via xsetroot or dwmblocks, etc.) and this status is _split_ based on a separator - what is on the left of the separator goes to the first status and what is on the right of the status goes to the second status.

The separator is by default a semicolon.
https://github.com/bakkeby/dwm-flexipatch/blob/a18f3ef370110c85d9001aced4b0cb1c96a075bf/config.def.h#L152-L154

So what you would need to do is to add a semicolon somewhere in the status for this to work.

**Comment by Zerogaku** [comment]
Hey thanks for the help, adding semicolon the output of one of my modules worked!

**Comment by Zerogaku** [comment]
Oh wait I forgot to ask, is it possible to toggle the extrabar?

**Comment by bakkeby** [comment]
No. You can toggle the display of the bars using `MOD+b`, but you can't toggle these individually.

**Comment by Zerogaku** [comment]
Can it be done with some tinkering? Or is dwm only able to toggle all the bars?

**Comment by bakkeby** [comment]
With tinkering almost anything is possible.

You'd want to have a flag like showbar associated with the bar rather than the monitor, then you'd have to make changes to `updatebarpos` to take the visibility of both bars into account when determining the size and position of the window area (as well as the position of each bar). Then you'd want to make changes to `togglefloating` such that would set that flag to be the same across all bars (likely based on the showbar value of the first bar).

Finally you'd want to make a function similar to `togglebar` that only toggles the showbar value for the second bar on the current monitor.

I think that would be it.

**Comment by Zerogaku** [comment]
Thanks for the advice!
