### ISSUE TITLE
Launcher patch

### ISSUE THREAD

**Issue by plasmoduck** [bakkeby/dwm-flexipatch#45]
Hey dude, can you add this patch please when you have time.
https://dwm.suckless.org/patches/launcher/
But create a new enum so each launcher created can have a different color, i.e; 'blue-surf green-spotifytui orange-firefox' etc

**Comment by bakkeby** [comment]
I have seen this patch, but it's not a particularly good one tbh (otherwise I'd have integrated it already). All the commands would be grouped together and you would not be able to have different colors per command.

There is already the statusbutton option and you could just create more of these if you want and you can have different actions depending on what mouse button you click. As an example I have a status button that launches a new terminal (due to lack of imagination) on left click and opens a context menu (via [xmenu](https://github.com/phillbush/xmenu)) on right click.

Alternatively you can achieve the same using dwmblocks + statuscmd and use status2d to control the colors. You could even split it off the normal status if you wanted to.

**Comment by plasmoduck** [comment]
Okay that sucks. It looks pretty cool & it's handy having a few launchers to the right of the layout button. I had a dwm build patched with it and I created a new color scheme for it so that each laucher I created can have a different color. But if its going to be a bitch to patch all good.

**Comment by bakkeby** [comment]
You can of course just patch it for your own build if you want, there is really not much to it. If you use the statusbutton as a base then it should be a breeze.
