### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by plasmoduck** [bakkeby/dwm-flexipatch#54]
Hi dude, can you make a pertag save layouts patch so whatever layout I set my tags to when I quit dwm the layouts are saved for the tags. Then when I start dwm next, the tags are the same layouts I last set them to instead of all reverting back to the first layout (tiled usually).

**Comment by bakkeby** [comment]
Technically it should be possible to extract and store the state of each tag, on each monitor, using the IPC patch and use that information to restore the layouts at a later point (or the next time dwm starts).

Or just use hibernate rather than shut down :) 

Let's say you were to implement this feature yourself, have you given any thoughts as to how you would go about achieving that?

I don't personally have any need or interest in something like this, at least not at this point in time, so I would have a hard time justifying spending time on it. It makes more sense to me to have everything predefined rather than trying to restore something that might be messy.

**Comment by plasmoduck** [comment]
I'm not talking about restoring any windows to dwm. Just saving each tags layout state. So they don't all reset back to the same layout each session. I wasn't sure how to go about it, that's why I asked you :p 

I found this rant "Why don't tags remember their layout" http://web.archive.org/web/20120120161931/http://lubutu.com/rant/dwm-faq

Which I don't fully agree with, the reason of using dwm with patches is so you can build an environment that works for you. I think tags remembering their layout each time they are changed is quite productive and saves time setting up each tags layout each time dwm starts.

If you got any tips how I can do it, I'm all ears. I'm happy to modify the existing pertag patch code in dwm-flexipatch to archive this if possible?

**Comment by bakkeby** [comment]
Yes, it's about "just" doing it.

This is dwm, the videogame, filled to the brim with puzzles and a load of DLCs.

What you want is a save feature, more so an auto-save feature, such that you can continue your quest where you left it with the caveat that monsters will respawn.

There are three main stages to this feature:

- capture the state of the game
- store the state of the game
- restore the state of the game

Great. All of this is _relatively_ easy to do in a failure prone way, but is rather involved to do properly.

**Capturing the state**
The layouts are stored in a Layout array `layouts[]` variable. Both the monitor and pertag refer to _addresses_ within this array, not just layout number 4. To capture the layouts of each tag you would have to do something like:

- loop through each monitor
- loop through each (per)tag
- loop through each of the layouts to try and work out what index in the layouts array the layout is referring to

**Storing the state**

So where do we store this information? In the cloud? In memory? Eureka! - we'll store it in a _file_. Now the problem is that we need to store the state captured in the previous step in such a way that we can read and process that information later. :thinking: OK, so store the tags in a comma separated line or whatever and we work out how to actually write to a file in C. Job done.

**Restoring the state**

Now we just read from that file, right? Sure, but now we just need a mechanism to _parse_ that specific format. We work that out, find out how to set the layout with the data we have read and voila task complete!

Phew! That was easy! That only took three days (or a week) of tinkering and testing to get right.

Now let's brag about it on reddit, karma++, some people really like the idea and start using it.

Then comes the things we did not foresee:

- feature request 1: it would be great if you could also store mfact? it's really part of the layout
- feature request 2: could you also include nmaster? thanks!
- complaint 1: I added a new layout and now dwm won't start
- complaint 2: I changed the layouts around and now all the restored layouts are wrong
- complaint 3: the patch remembers layouts for tags, but it is weird, it doesn't remember it for the first tag until I navigate to another tag and back again
- complaint 4: I did a `shutdown -r now` and my layouts did not get stored
- complaint 5: I worked without my second monitor yesterday and today all the layouts I set on the second monitor are gone!
- feature request 3: I use the pertagbar patch, could you include information about whether the bar is shown?
- complaint 6: I have three monitors, one of them is vertical, your patch sucks because it doesn't remember which monitor is which monitor
- feature request 4: the storing and restoring of tags work great, but I don't want the those tags that I have pre-configured using monitorrules to be affected
- complaint 7: I don't like the auto-save feature, can you make it so that it only saves when I tell it to save?
- complaint 8: I like this feature, but I would like to edit the save file manually, can you make it more human readable?
- feature request 5: saving the tag layout is great, but can you do the same for all the other settings that can be toggled?
- complaint 9: the change you made for complaint 7 broke my workflow, I have a script that sets the first tag to a random layout
- feature request 6: could you port this to dwm 6.0? I can't remember what patches I have applied and I'm in no position to upgrade, thanks
- complaint 10: I now only use pertag without the bar, and your patch seems to have stopped saving / restoring layouts. When I enable pertag with the bar all my layout setup is gone. Help!
- complaint 11: I have 15 tags in my build and your patch only seem to save and restore the first 9
- complaint 12: where is the documentation for this feature?

In conclusion development and long term support can stack up in terms of effort and time spent. Dealing with most of the above cases upfront makes the initial development time significantly longer. The feature can be convenient for those that rely on it.

As for the approach for implementing something like this there are two main options:

- implement it as a feature within dwm or
- implement it via an external script

The benefit of implementing it within dwm is that you can make it seamless so that the end user won't notice layouts being stored or restored.

As-is doing it with an external script may mean that you would have to switch to each tag on each monitor in order to retrieve what layout and other settings are set for that tag. This would cause visual flickering for the end user while the script checks each tag. It might be able to expand the IPC patch to make it expose the pertag settings in a more convenient way.

The benefit of implementing this as an external script is that you can use the programming language of choice which would make certain aspects of this easier to implement (e.g. parse and use JSON objects / data, formatting the settings to persist them in a save file, parsing the formatted data from the save file on load) and for the most part it would be a standalone tool that would not be tied to a specific build of dwm.

**Comment by plasmoduck** [comment]
Wow I wasn't expecting all that. Very informative. Thanks for the effort. Sounds like its probably a LOT more work than it's really worth. I think I'll just stick with what I have.
