### ISSUE TITLE
Different colors for each tag

### ISSUE THREAD

**Issue by plasmoduck** [bakkeby/dwm-flexipatch#55]
How can I create seperate color schemes for each tag? Say all tags bg the same bug tag1 is red tag2 is green tag3 is yellow etc?

**Comment by bakkeby** [comment]
This is what sets the scheme for the tag by default, it can either be selected, urgent or (tags) normal.
https://github.com/bakkeby/dwm-flexipatch/blob/master/patch/bar_tags.c#L51-L57

Instead of `SchemeTagsNorm` you could choose another scheme that depends on the variable `i`.

Let's say that you'd introduce your own schemes `SchemeTagNormA`, `SchemeTagNormB`, ..., `SchemeTagNormI` (in order) then you could replace that `SchemeTagsNorm` with `SchemeTagNormA + i`.

You could do the same with the selected color as well.

**Comment by plasmoduck** [comment]
Awesome! Thanks :)
