### ISSUE TITLE
systray background is more transparent than the rest of panel.

### ISSUE THREAD

**Issue by AtifChy** [bakkeby/dwm-flexipatch#58]
![Screenshot_20201012_024011](https://user-images.githubusercontent.com/42291930/95689700-61963a00-0c34-11eb-8966-aae3f25ef7b1.png)
with systray, barpadding & alpha patch

**Comment by bakkeby** [comment]
Hi @AtifChy,

actually the systray is a separate window whose background is fully transparent because it is displayed on top of the bar window.

I assume that you are using `picom` as your compositor and that you have blur enabled resulting in the systray background being blurred against the bar background which is also blurred.

If that is the case then I'd recommend adding `"class_g = 'dwmsystray'",` to the `blur-background-exclude` setting in your picom.conf file. You should also add that to the `shadow-exclude` setting to avoid that double shadow.

\
Thanks,

-Stein

**Comment by AtifChy** [comment]
wow. Thanks. I guess you know everything.
