### ISSUE TITLE
2 borders like 2bwm

### ISSUE THREAD

**Issue by plasmoduck** [bakkeby/dwm-flexipatch#61]
I've been looking at 2bwm https://github.com/venam/2bwm/find/master and I quite like how it draws 2 borders https://github.com/venam/2bwm/find/master Is there anything like this for dwm? I was looking at the wmutils/opt utilities and found chwb2 - control two different window borders https://github.com/wmutils/opt Can I use this with dwm?

**Comment by bakkeby** [comment]
Not sure if I would trust someone who's username and hostname add up to **stick@ur-anus** \[[ref](https://camo.githubusercontent.com/8921212f7e07275a2b33ce4af3c42fdb9c55762a/68747470733a2f2f76656e616d2e6e69786572732e6e65742f626c6f672f6173736574732f7363726f74732f31372e706e67)\], but it's entirely up to you.

I have not come across any patches that would add a double border for dwm.

dwm uses XSetWindowBorder and lets X handle the drawing of the window border (as far as I understand it), whereas something like 2bwm manually draws the borders \[[ref](https://github.com/venam/2bwm/blob/master/2bwm.c#L1890)\].

I tried the wmutils' opt **chwb2** utility, and I can confirm that this works with dwm - you just need to remove / comment out the relevant lines that call XSetWindowBorder in your build. You would need to find a way to re-trigger the command whenever the window is resized though - otherwise the bottom and right borders will be cut off.

Example command:
```
chwb2 -O 00ff33 -I ff0ff0 -i 2 -o 3 0x2200002
```

Also it's a bit weird, if you drag such a window above a white window then the border is white - this I believe have to do with that the colors set by chwb2 do not have an alpha channel set and the compositor (picom in my case) makes it transparent (not an issue of course if you do not use a compositor).

**Comment by plasmoduck** [comment]
the command chwb2 -O 00ff33 -I ff0ff0 -i 2 -o 3 0x2200002 just returns clean without drawing an extra border in my terminal

**Comment by plasmoduck** [comment]
Also, checkout the contrib repo of wmutils theres a nice script called 'rainbow.sh' that makes the active windows border cycle rainbow colors. It works well with flashfocus :)

**Comment by bakkeby** [comment]
Is the window ID of your terminal 0x2200002? That would be quite a coincidence :)

**Comment by plasmoduck** [comment]
Well I tried it again using xwininfo and clicking on another st window
then using that window id: xwininfo: Window id: 0x3400006 "~" like so:

chwb2 -O 00ff33 -I ff0ff0 -i 2 -o 3 0x3400006
but I get
chwb2: warning: pixmap is greater than border size

**Comment by bakkeby** [comment]
That warning shouldn't matter, but it's related to the inner size of 2 + the outer size of 3 so the client is expected to have a window border of at least 5 pixels.

For me the command did not appear to do anything for me until I commented out the XSetWindowBorder lines in dwm, or rather, putting the command in a loop gave me a flickering border as X overwrites it.

**Comment by plasmoduck** [comment]
Which XSetWindowBorder lines exactly do I need to comment out?

**Comment by bakkeby** [comment]
Go forth, experiment.

I would start with commenting out all of them.
