### ISSUE TITLE
Got this compiling error 

### ISSUE THREAD

**Issue by Gako358** [bakkeby/dwm-flexipatch#76]
Hei

Got this compiling warning, what can i do.

``
patch/bar_status.c:30:1: warning: ‘click_status’ defined but not used [-Wunused-function]
   30 | click_status(Bar *bar, Arg *arg, BarArg *a)
      | ^~~~~~~~~~~~
patch/bar_status.c:16:1: warning: ‘draw_status’ defined but not used [-Wunused-function]
   16 | draw_status(Bar *bar, BarArg *a)
      | ^~~~~~~~~~~
patch/bar_status.c:2:1: warning: ‘width_status’ defined but not used [-Wunused-function]
    2 | width_status(Bar *bar, BarArg *a)
      | ^~~~~~~~~~~~

**Comment by bakkeby** [comment]
Hi @Gako358,

this suggests that you have `BAR_STATUS_PATCH` enabled in `patches.h` (it is enabled by default), but the functions are not used.

This is most likely because you have enabled `BAR_STATUS2D_PATCH` or `BAR_POWERLINE_STATUS_PATCH` which takes precedence.
https://github.com/bakkeby/dwm-flexipatch/blob/bd5db9e63f5f7c2c659e68151f2ae8ca5cc8fb18/config.def.h#L455-L465

Just set `BAR_STATUS_PATCH` to 0 in `patches.h` and you should be good to go.

\
Thanks,

-Stein

**Comment by Gako358** [comment]
Ok, I have the powerline patch, so prob why. I will set it to 0 as you said. Tusen takk!

**Comment by bakkeby** [comment]
It is just a compilation warning, it doesn't actually prevent dwm from being compiled.

**Comment by Gako358** [comment]
I am aware, but I hate warnings, in a perfect compiling world, warnings are to be removed/fixed, except in GTK environment, where warnings are way of life :-1:

**Comment by Gako358** [comment]
One last question while trying out this version of dwm, btw fantastic job on this. 
The status bar do not follow to other monitors and the powerline tags does not follow to other monitors either, do you have an idea what i am missing here?

**Comment by Gako358** [comment]
disregard, i got it working. My bad for not reading..
