### ISSUE TITLE
Dmenu related

### ISSUE THREAD

**Issue by Gako358** [bakkeby/dwm-flexipatch#77]
Hey again, I got a dmenu issue, but i do believe its related to dwm. I use a 3 screen setup, and when i use dmenu, it shows on the next screen, so if i am on screen 0, it will be popping on screen 1. I do use the center patch for dmenu. Do you have any clue what is wrong?

Another question, regarding the extrabar, is it a way to draw the background color separate from the top bar?

Any help would be much appreciated!

**Comment by Gako358** [comment]
another question, this will be the last...

When i try open ncmpcpp with a scratchpad, how to i assign it so that it will open the player in the scratchpad. I have tried with st -e ncmpcpp but the screen flashed and nothing happens..

Now i have it like this
```
const char *spcmd3[] = {"st", "-n", "ncmterm",  "-g", "120x55", NULL };
```

then i just type in manual.

**Comment by bakkeby** [comment]
About the dmenu issue, it is not one that I have experienced myself before.

Do you have the `NODMENU_PATCH` enabled, it is a patch that removes the `-m dmenumon` argument when launching dmenu.
https://dwm.suckless.org/patches/nodmenu/dwm-nodmenu-6.2.diff

Other than that do you have the `SORTSCREENS_PATCH` enabled? It changes the order of the monitors such that monitor 0 is always the leftmost monitor (as opposed to the primary one).

Other than that, try and see if changing the order in xrandr makes any difference.

----

About ncmpcpp, this seems to open correctly in the terminal at least.
```bash
st -e ncmpcpp
```
If I run it with the `-g 120x55` then it crashes.
```bash
$ st -e ncmpcpp -g 120x55
child exited with status 1
```
Probably because
```bash
$ ncmpcpp -g 120x55
Error while processing configuration: unrecognised option '-g'
```
Perhaps try this?
```bash
st -g 120x55 -e ncmpcpp
```

-----

 > regarding the extrabar, is it a way to draw the background color separate from the top bar?

Out of the box no, but it shouldn't be too difficult to add if you want to tinker.

In the `drawbarwin` function there is a line
```c
drw_setscheme(drw, scheme[SchemeNorm]);
```

You can set up a new scheme (that's trivial btw) and choose the scheme based on whether the bar is drawn on the top or bottom.

E.g. something like:
```c
if (bar->topbar)
     drw_setscheme(drw, scheme[SchemeNorm]);
else
     drw_setscheme(drw, scheme[SchemeBottomBarColorFantastic]);
```
or
```c
drw_setscheme(drw, scheme[(bar->topbar ? SchemeNorm : SchemeBottomBarColorFantastic)]);
```

-----

And no, it is not going to be your last question :)

**Comment by Gako358** [comment]
Removed the screensort and dmenu issue is gone. Make sense, could prob have changed it in xrandr also.
Got scratchpads working, with
```
const char *spcmd3[] = {"st", "-n", "ncmterm",  "-g", "120x55", "-e", "ncmpcpp", NULL };
```

Also managed to get the bottom bar working, however there was a issue with resizing when using the lower bar, back to only top bar for now, will look into this later.

Thank again for your help!

Takk, god helg

**Comment by Gako358** [comment]
Right you are, another problem i cannot solve. I got the Steam patch installed, but i do not know if that is the problem. When i open chat in steam, and or try to check out a game in store by right clicking a friend in steam chat, dwm quits, and i am back in tty. xorg logs say computer to slow, and after reading a bit, xorg will shutdown dwm, if this happens. Ram is fine, no leaks. I just do not get it.

**Comment by bakkeby** [comment]
I'm not sure how to debug that one, I wasn't able to replicate this myself.
You could try disabling that Steam patch to see if that makes any difference - all it does is ignoring Steam's requests to change position and size so I wouldn't have thought that would make any difference.

Perhaps try replicating the issue via `Xephyr`, that way you see the output of dwm straight in your terminal.

For the real deal you may also want to capture stdout / stderr when you run dwm so that you can have a log file to refer to, which is very useful should you want to add print statements for debugging purposes.

**Comment by Gako358** [comment]
ok, good morning!
I am trying to get Xephyr up and running, but how do I solve the problem about same modkey, when I try to run anything from within the Xephyr, it launces on the host.

Btw it was not the steam patch, and it happens everytime i try to go to a friends profile, via the friends list.

**Comment by Gako358** [comment]
```
Job 2, “dwm &” terminated by signal SIGSEGV (Address boundary error)
```
Had to use Ctrl+Shift to tell Xephyr to  use keyboard

Anyway, Segfault when opening up a another window.. I will have to investigate, maybe try replicated this with clean install.

**Comment by bakkeby** [comment]
Yes `Ctrl+Shift` is the trick, before I figured that out I used a different MOD key when compiling for running in Xephyr.

Don't run `dwm &`, just run `dwm` - that way you get to see anything dwm spits out.

**Comment by Gako358** [comment]
```
[1121/120804.437875:ERROR:frame_sink_video_capturer_impl.cc(206)] Invalid resolutions constraints: 0x0 must not be greater than 0x0; and also within media::limits.
[1121/120808.893292:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
fish: Job 2, “dwm” terminated by signal SIGSEGV (Address boundary error)
```

This is all i got, i am setting up fresh now, must be something i`ve done, since it works in a clean install.

**Comment by bakkeby** [comment]
This maybe? 
https://github.com/ValveSoftware/steam-for-linux/issues/7450

Could depend on the distribution you are running, and the version of Steam.

**Comment by Gako358** [comment]
No, I do not think so, When i compile a fresh flexipatch dwm, with all the patches I`ve choosen in my main build, but without all the thinkering i`ve done in config.def.h, then its working. So must be me, difficult to tell, but I am re-compiling a fresh install now. Will write if I discover anything

**Comment by bakkeby** [comment]
Interestingly while the Friends List window is open X, and in turn dwm, is spammed with _VARIABLE_REFRESH property notify requests for both Steam and the Friends List.

**Comment by Gako358** [comment]
Still should not segfault, could I run dwm in gdb, I am guessing it will destroy my machine, but still would be funny to see what happens.

**Comment by bakkeby** [comment]
If you happen to use slack and want to chat we have a (very) small group aptly called [segfault](https://join.slack.com/t/segfault-talk/shared_invite/zt-fmdoeghe-p_l0eepALcDQvlDO6iOjsw).

**Comment by Gako358** [comment]
I have not used slack in some time, I will set it up after i get done debugging here. However it seem to work, now. Still do not make sense yet what it is I did. Thnak you Stein Gunnar for the help so far, and yes you where 100% correct with me asking more questions :+1:

**Comment by Gako358** [comment]
Can close this, I have got everything working. No more segfaults, however... I do not know what went wrong last time around.
Story of my life..
