### ISSUE TITLE
Send terminal running process to scratchpad.

### ISSUE THREAD

**Issue by plasmoduck** [bakkeby/dwm-flexipatch#79]
Any way to send a terminal running process to the scratchpad, so I can press MOD+GRAVE and the process that was running in a terminal pops up in a scratch pad?

**Comment by bakkeby** [comment]
That does not make much sense to me. Scratchpads don't work with processes.

**Comment by plasmoduck** [comment]
Say for example if I open st and start vim, is there anyway I can make dwm send that vim session to the scratchpad with MOD+something?

**Comment by bakkeby** [comment]
Sending a running process from one terminal to another is typically restricted by the kernel unless you set `/proc/sys/kernel/yama/ptrace_scope` to 0 (opens some vulnerabilities).

While it is possible to do this, it would have to be something that you handle in the two terminals (e.g. putting the application in the background in one, and putting it in the foreground with the other using something like `reptyr`).

It is easier to just push the terminal itself to the scratchpad imho. In order to send something to the scratchpad you will need to have a window, more specifically a client window that is handled by dwm.

Pushing something to the scratchpad is not particularly complicated, you just need to read and understand how the scratchpad flavour of choice works.

Gaspar Vardanyan's [scratchpad](https://github.com/GasparVardanyan/dwm-scratchpad) does this for example (`SCRATCHPAD_ALT_1_PATCH`).

I also modified Christian Tenllado's multiple [scratchpads](https://dwm.suckless.org/patches/scratchpads/) patch to support assigning windows to a given scratchpad.
https://github.com/bakkeby/dwm-flexipatch/blob/76292ba325278a38bf8a486b118468a7c6e151c2/patch/scratchpad.c#L12-L21

https://github.com/bakkeby/dwm-flexipatch/blob/76292ba325278a38bf8a486b118468a7c6e151c2/config.def.h#L898-L902

As an example if I do `MOD+t` then that brings up a terminal, but if I do `MOD+Ctrl+t` on any window then that window will now be the designated scratchpad instead of the terminal.

If you use the named scratchpads patch then the principle is the same, you just need to set the `scratchkey` variable of the client window.

If you have multiple windows on the same scratchpad then you'd have to decide how that should work. Gaspar Vardanyan's version only show the last window sent to the scratchpad whereas for the scratchpads one all windows on the scratchpad is shown together.

**Comment by plasmoduck** [comment]
Assigning windows to a given scratchpad: This is just what I was looking for, thanks. I want to use it in a sinario where I may start a system/software update or pkg download in a terminal then I want to send it to a scratchpad to hide it and then if I switch tags I can big it back when I need it.
