### ISSUE TITLE
Do not compile with only 3 patches activated ...

### ISSUE THREAD

**Issue by MrMic** [bakkeby/dwm-flexipatch#91]
Hi,

I have enabled the patches:
- alpha
- autostart
- systray

And get this with make
```
dwm build options:
CFLAGS   = -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2   -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -DVERSION="6.2" -DXINERAMA
LDFLAGS  = -L/usr/X11R6/lib -lX11 -lXinerama -lfontconfig -lXft        
CC       = cc
cp config.def.h config.h
cp patches.def.h patches.h
cc -c -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2   -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -DVERSION=\"6.2\" -DXINERAMA drw.c
cc -c -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2   -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -DVERSION=\"6.2\" -DXINERAMA dwm.c
In file included from patch/include.c:95,
                 from dwm.c:732:
patch/autostart.c: In function ‘runautostart’:
patch/autostart.c:65:3: warning: ignoring return value of ‘system’, declared with attribute warn_unused_result [-Wunused-result]
   65 |   system(path);
      |   ^~~~~~~~~~~~
patch/autostart.c:79:3: warning: ignoring return value of ‘system’, declared with attribute warn_unused_result [-Wunused-result]
   79 |   system(strcat(path, " &"));
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~
cc -c -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2   -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -DVERSION=\"6.2\" -DXINERAMA util.c
cc -o dwm drw.o dwm.o util.o -L/usr/X11R6/lib -lX11 -lXinerama -lfontconfig -lXft        
/bin/ld: dwm.o: undefined reference to symbol 'XRenderFindVisualFormat'
/bin/ld : /lib/x86_64-linux-gnu/libXrender.so.1 : erreur lors de l'ajout de symboles : DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [Makefile:35 : dwm] Erreur 1

```
I do not touch anything.
System: Ubuntu 20.04

Any idea ?

Rgds,

**Comment by bakkeby** [comment]
The way this works is that there are pre-processors that determine what code is being included during compile time depending on what you have enabled in `patches.h`.

These pre-processor directives don't, however, work for the scripts that initiate the compile. There are a handful of patches that depend on additional libraries to compile, and the `alpha` patch is one of them.

In `patches.h` where you enable the patch there is a comment that says that the alpha patch depends on the Xrender library.

https://github.com/bakkeby/dwm-flexipatch/blob/acbf2de1c23085e0a8736498e5c7600f77f7a5f0/patches.def.h#L168-L173

So in order for to compile this you just need to uncomment this line in `config.mk`:

https://github.com/bakkeby/dwm-flexipatch/blob/acbf2de1c23085e0a8736498e5c7600f77f7a5f0/config.mk#L25-L26

(btw, I'd recommend having a look at the [cool_autostart](https://dwm.suckless.org/patches/cool_autostart/) patch rather than the [autostart](https://dwm.suckless.org/patches/autostart/) one as the former is easier to work with imho)

**Comment by MrMic** [comment]
Hi,

Thanks for the tips.
I will try all this tonight.
sorry for the noise, i didn't know.

Rgds,

**Comment by MrMic** [comment]
Hi,

Indeed all is fine now.
Thank you very much for all your advices( autostart ...).
You have done a wonderful project. Congrats.

Rgds,
