### ISSUE TITLE
 hide content of windows when moving and resizing

### ISSUE THREAD

**Issue by plasmoduck** [bakkeby/dwm-flexipatch#92]
Hi bakkeby, is there some way I can change to behaviour of dwm to hide content of windows when moving and resizing floating windows and only show the border/frame?

**Comment by bakkeby** [comment]
Not easily no.

The primary reason being that dwm does not have reparenting of windows - as in a wrapper window that draws the border and adds `_ [] X` buttons etc.

If I was serious about such a feature then I would probably create a new dummy window that has a border but is otherwise 100% transparent that I would "replace" the other window with for the duration of the resize / move. This is doable, but you'd need to have a good idea of how everything works and and what you are doing to pull this one off.

A compromise could be to use the [clientopacity](https://dwm.suckless.org/patches/clientopacity/) patch where you artificially set the opacity to, say, 50% for the duration of the move, then restore it to what it previously was when you are finished moving the window. This gives a pretty nice effect, with the caveat that as the border is part of the window it too will be as transparent as the window is.

**Comment by plasmoduck** [comment]
Is it possible to automate the process using the clientopacity patch so the opacity automatically goes to 50% for the move then restores to 100% when mouse is depressed?

**Comment by bakkeby** [comment]
Yes I guess that would be the point.

If you have the clientopacity patch applied then you'd want to make a note of the opacity that a client had before you started moving it so that you can restore it later on. You'd end up something along these lines:

```diff
diff --git a/config.def.h b/config.def.h
index 1c0b587..ed2c9e1 100644
--- a/config.def.h
+++ b/config.def.h
@@ -1,6 +1,7 @@
 /* See LICENSE file for copyright and license details. */

 /* appearance */
+static const double moveresizeopacity = 0.5;    /* client opacity when being moved or resized */
 static const unsigned int borderpx  = 1;        /* border pixel of windows */
 static const unsigned int snap      = 32;       /* snap pixel */
 static const int showbar            = 1;        /* 0 means no bar */
diff --git a/dwm.c b/dwm.c
index 4465af1..35cef07 100644
--- a/dwm.c
+++ b/dwm.c
@@ -1140,11 +1140,15 @@ movemouse(const Arg *arg)
        Monitor *m;
        XEvent ev;
        Time lasttime = 0;
+       double prevopacity;

        if (!(c = selmon->sel))
                return;
        if (c->isfullscreen) /* no support moving fullscreen windows by mouse */
                return;
+
+       prevopacity = c->opacity;
+       opacity(c, moveresizeopacity);
        restack(selmon);
        ocx = c->x;
        ocy = c->y;
@@ -1190,6 +1194,7 @@ movemouse(const Arg *arg)
                selmon = m;
                focus(NULL);
        }
+       opacity(c, prevopacity);
 }

 Client *
@@ -1295,11 +1300,15 @@ resizemouse(const Arg *arg)
        Monitor *m;
        XEvent ev;
        Time lasttime = 0;
+       double prevopacity;

        if (!(c = selmon->sel))
                return;
        if (c->isfullscreen) /* no support resizing fullscreen windows by mouse */
                return;
+
+       prevopacity = c->opacity;
+       opacity(c, moveresizeopacity);
        restack(selmon);
        ocx = c->x;
        ocy = c->y;
@@ -1342,6 +1351,7 @@ resizemouse(const Arg *arg)
                selmon = m;
                focus(NULL);
        }
+       opacity(c, prevopacity);
 }

 void
```

If you use picom then I think you'll need the `detect-client-opacity` setting set to true for the clientopacity patch to work. It seems to work out of the box with xcompmgr.

**Comment by plasmoduck** [comment]
Awesome thanks
