### ISSUE TITLE
fullscreen patch

### ISSUE THREAD

**Issue by haluk** [bakkeby/dwm-flexipatch#95]
I have my `st` in second tag, and only want to make `st` in second tag fullscreen. If I use `fullscreen` patch, and pressed `Mod | Shift - f`, it shows the window fullscreen but it also disables bar for other tags. I tried `fullfakescreen` patch but it doesn't make `st` full screen.

**Comment by bakkeby** [comment]
This is relatively straghtforward, there are just so many fullscreen patches that it is easy to get lost in the mix.

The `fullscreen` patch is a very old one which simply sets the layout to be monocle and hides the bar. This in combination with the pertag patch that includes the (visibility of the) bar could in principle solve your problem.

The `fakefullscreen` patch lets windows go fullscreen within their allocated space (i.e. the size and position when tiled) - this can be used for example to play a fullscreen video within the tiled space instead of taking up the whole screen. The `fakefullscreenclient` is the same just that you can enforce fake fullscreen on a per client basis.

What you are really after is the `togglefullscreen` patch which is the same as the differently named [actualfullscreen](https://dwm.suckless.org/patches/actualfullscreen/) patch on the suckless site. This just gives you a simple keybinding to toggle fullscreen for the window (this would be the same as pressing `F11` in firefox which removes the address bar, bookmarks, etc. whereas the `fullscreen` would just make the browser take up the whole screen.

That said I would also recommend the `losefullscreen` patch. The gist of it is that if you have a fullscreen window then that one will lose fullscreen if another client on the same tag gets focus. This can happen if you have multiple windows and you use the MOD+j/k keyboard shortcuts or you spawn a new terminal. What happens in this case without this patch is that the new terminal gets focus, but you can't see anything as the fullscreen window blocks the view of everything - and you have to fiddle with MOD+j/k to get the focus back on the fullscreen window so that you can exit fullscreen. An alternative would be the [alwaysfullscreen](https://dwm.suckless.org/patches/alwaysfullscreen/) patch which aims to prevent focus from going away from the fullscreen window - but this does not protect against a new terminal getting focus.

If you ever find yourself in the business of patching your own build from scratch then I'd recommend the [fullscreen-compilation](https://github.com/bakkeby/patches/wiki/fullscreen-compilation) patch which addresses most of the bugs and obscurities that comes with fullscreen and fake fullscreen windows in a tiling window manager setting.

**Comment by haluk** [comment]
Thanks. I was able to patch `fullscreen-compilation`. It works. However, there is only subtle unexpected behavior. If alpha patch is applied, st in fullscreen still shows the status bar beneath.

**Comment by bakkeby** [comment]
Is that really what you'd expect? The window is transparent so you'll see everything that is beneath it, including other windows. This is the case for the monocle layout as well. 

There's also something that is called pseudo-transparency that just shows the wallpaper as part of the transparency effect, which with picom you allegedly can enable with `--experimental-backends --transparent-clipping` (I say allegedly because I haven't had a chance to test and confirm).

**Comment by haluk** [comment]
`st` is not shown transparent with `--transparent-clipping` flag. I also tried `--experimental-backends, I still see the bar in fullscreen-mode. Is there a way to change st alpha level it's started?

**Comment by bakkeby** [comment]
This seems to work fine.

![image](https://user-images.githubusercontent.com/1438008/108619864-ffdaad80-7427-11eb-9f3b-48ea5cbaedcb.png)
 
The alpha patch for st allows you to have a transparent background while the text remains opaque - I am not aware of any patch that let's you change this transparency on the fly.

You can control the opacity of windows externally with tools such as `picom-trans`, but that will make the text transparent as well so it is not always ideal.

**Comment by haluk** [comment]
My bad. I didn't enable both flags together. It's what I expect now.

Thanks.
