### ISSUE TITLE
Layouts not working

### ISSUE THREAD

**Issue by H4XTag** [bakkeby/dwm-flexipatch#97]
Hi. Newbie here. I added `GRIDMODE_LAYOUT` and both fibonacci layouts. Yet when I press the keyboard shortcuts mentioned on the suckless page it does not reflect. Any help will be appreciated.

**Comment by bakkeby** [comment]
Yes there are two parts to this, the first is that this build is combining many different patches and many of them have conflicting keybindings (many patches want to use `MOD+r` for example).

Because of this keybindings for the different patches are set to avoid conflicts as far as possible, so you would need to refer to the bindings in `config.h` rather than what is stated on the suckless page.

The other part is that keybindings for layouts are based on indices, e.g.
https://github.com/bakkeby/dwm-flexipatch/blob/27185a74c4b2311350d029b5aefaa326dd143adf/config.def.h#L903-L905

and given that each layout is optional one can't know up front which index e.g. the gridmode layout will end up as.

https://github.com/bakkeby/dwm-flexipatch/blob/27185a74c4b2311350d029b5aefaa326dd143adf/config.def.h#L591-L639

Because of this predefined keyboard shortcuts can't be set. 

You can add your own keybindings for as many layouts that you have (`{.v = &layouts[3]} },` onward), but just be aware that if you have a keybinding that refers to an index that doesn't exist then dwm will crash when you use it - that's just the nature of referring to data that does not exist in memory.

**Comment by H4XTag** [comment]
Thank you very much for the quick reply! I can confirm that it is working now :)
